python ValidateBDT.py  -b Fake -c BDTA -f EE  -e BDTAEta_0
python ValidateBDT.py  -b Fake -c BDTA -f EE  -e BDTAEta_1
python ValidateBDT.py  -b Fake -c BDTA -f EE  -e BDTAEta_2
python ValidateBDT.py  -b Fake -c BDTA -f MuMu  -e BDTAEta_0
python ValidateBDT.py  -b Fake -c BDTA -f MuMu  -e BDTAEta_1
python ValidateBDT.py  -b Fake -c BDTA -f MuMu  -e BDTAEta_2
python ValidateBDT.py  -b Conv -c BDTA -f EE  -e BDTAEta_0
python ValidateBDT.py  -b Conv -c BDTA -f EE  -e BDTAEta_1
python ValidateBDT.py  -b Conv -c BDTA -f EE  -e BDTAEta_2
python ValidateBDT.py  -b Conv -c BDTA -f MuMu  -e BDTAEta_0
python ValidateBDT.py  -b Conv -c BDTA -f MuMu  -e BDTAEta_1
python ValidateBDT.py  -b Conv -c BDTA -f MuMu  -e BDTAEta_2
python ValidateBDT.py  -b CF -c BDTA -f EE  -e BDTAEta_0
python ValidateBDT.py  -b CF -c BDTA -f EE  -e BDTAEta_1
python ValidateBDT.py  -b CF -c BDTA -f EE  -e BDTAEta_2
