./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/QCD_Pt_300to470_TuneCP5_13TeV_pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/QCD_Pt_3200toInf_TuneCP5_13TeV_pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/QCD_Pt_470to600_TuneCP5_13TeV_pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/QCD_Pt_600to800_TuneCP5_13TeV_pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/QCD_Pt_800to1000_TuneCP5_13TeV_pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/ST_t-channel_antitop_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/TTToHadronic_TuneCP5_13TeV-powheg-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/WWW_4F_TuneCP5_13TeV-amcatnlo-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/WWZ_4F_TuneCP5_13TeV-amcatnlo-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/WW_TuneCP5_13TeV-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/WZZ_TuneCP5_13TeV-amcatnlo-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/WZ_TuneCP5_13TeV-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/ZZZ_TuneCP5_13TeV-amcatnlo-pythia8
./bin/UpdateSampleForSNU.sh /gv0/DATA/SKFlat/Run2UltraLegacy_v3/2016postVFP/MC_SkimTree_LRSMTau/ZZ_TuneCP5_13TeV-pythia8