#define SKFlatNtuple_cxx
#include "SKFlatNtuple.h"
#include <TH2.h>
#include <TStyle.h>
#include <TCanvas.h>

void SKFlatNtuple::Loop(){

  Long64_t nentries = fChain->GetEntries();
  //nentries = 1000;
  //cout << "nentries = " << nentries << endl;

  if(MaxEvent>0){
    nentries = std::min(nentries,MaxEvent);
  }

  //==== Before starting the loop, print setups
  cout << "[SKFlatNtuple::Loop] MaxEvent = " << MaxEvent << endl;
  cout << "[SKFlatNtuple::Loop] NSkipEvent = " << NSkipEvent << endl;
  cout << "[SKFlatNtuple::Loop] LogEvery = " << LogEvery << endl;
  cout << "[SKFlatNtuple::Loop] IsDATA = " << IsDATA << endl;
  cout << "[SKFlatNtuple::Loop] DataStream = " << DataStream << endl;
  cout << "[SKFlatNtuple::Loop] MCSample = " << MCSample << endl;
  cout << "[SKFlatNtuple::Loop] IsFastSim = " << IsFastSim << endl;
  cout << "[SKFlatNtuple::Loop] Era = " << GetEra() << endl;
  cout << "[SKFlatNtuple::Loop] xsec = " << xsec << endl;
  cout << "[SKFlatNtuple::Loop] sumW = " << sumW << endl;
  cout << "[SKFlatNtuple::Loop] sumSign = " << sumSign << endl;
  cout << "[SKFlatNtuple::Loop] Userflags = {" << endl;
  for(unsigned int i=0; i<Userflags.size(); i++){
    cout << "[SKFlatNtuple::Loop]   \"" << Userflags.at(i) << "\"," << endl;
  }
  cout << "[SKFlatNtuple::Loop] }" << endl;


  cout << "[SKFlatNtuple::Loop] Event Loop Started " << printcurrunttime() << endl;

  for(Long64_t jentry=0; jentry<nentries;jentry++){

    if(jentry<NSkipEvent){
      //cout << "[SKFlatNtuple::Loop] Skipping " << jentry << "'th event" << endl;
      //exit(EXIT_FAILURE);
      continue;
    }

    if(jentry%LogEvery==0){
      cout << "[SKFlatNtuple::Loop RUNNING] " << jentry << "/" << nentries << " ("<<100.*jentry/nentries<<" %) @ " << printcurrunttime() << endl;
    }

    if(fChain->GetEntry(jentry)<0) exit(EIO);

    beginEvent();
    executeEvent();
    endEvent();

    //std::cout << jentry << " :" << muon_pt->size() << std::endl;

  }

  cout << "[SKFlatNtuple::Loop] LOOP END " << printcurrunttime() << endl;

}

//==== Basic

SKFlatNtuple::SKFlatNtuple(){
  MaxEvent = -1;
  NSkipEvent = 0;
  LogEvery = 1000;
  IsDATA = false;
  DataStream = "";
  MCSample = "";
  IsFastSim = false;
  SetEra("2017");
  xsec = 1.;
  sumW = 1.;
  sumSign = 1.;
  Userflags.clear();
}

SKFlatNtuple::~SKFlatNtuple()
{
  if (!fChain) return;
  delete fChain->GetCurrentFile();
  cout << "[SKFlatNtuple::~SKFlatNtuple] JOB FINISHED " << printcurrunttime() << endl;
}

Int_t SKFlatNtuple::GetEntry(Long64_t entry)
{
// Read contents of entry.
  if (!fChain) return 0;
  return fChain->GetEntry(entry);
}

TString SKFlatNtuple::GetEraShort() const
{
  if(DataEra=="2016preVFP") return "2016a";
  else if(DataEra=="2016postVFP") return "2016b";
  else return DataEra;
}

void SKFlatNtuple::Init()
{

  //std::cout << "[SKFlatNtuple::Init] called" << std::endl; 

  // Set object pointer
  HLT_TriggerName = 0;
  jet_pt = 0;
  jet_eta = 0;
  jet_phi = 0;
  jet_charge = 0;
  jet_area = 0;
  jet_partonFlavour = 0;
  jet_hadronFlavour = 0;
  jet_GenHFHadronMatcher_flavour = 0;
  jet_GenHFHadronMatcher_origin = 0;
  jet_DeepCSV = 0;
  jet_DeepCSV_CvsL = 0;
  jet_DeepCSV_CvsB = 0;
  jet_DeepJet = 0;
  jet_DeepJet_CvsL = 0;
  jet_DeepJet_CvsB = 0;
  jet_chargedHadronEnergyFraction = 0;
  jet_neutralHadronEnergyFraction = 0;
  jet_neutralEmEnergyFraction = 0;
  jet_chargedEmEnergyFraction = 0;
  jet_muonEnergyFraction = 0;
  jet_chargedMultiplicity = 0;
  jet_neutralMultiplicity = 0;
  jet_tightJetID = 0;
  jet_tightLepVetoJetID = 0;
  jet_partonPdgId = 0;
  jet_vtxNtracks = 0;
  jet_m = 0;
  jet_energy = 0;
  jet_PileupJetId = 0;
  jet_shiftedEnUp = 0;
  jet_shiftedEnDown = 0;
  jet_smearedRes = 0;
  jet_smearedResUp = 0;
  jet_smearedResDown = 0;
  jet_bJetNN_corr = 0;
  jet_bJetNN_res = 0;
  jet_cJetNN_corr = 0;
  jet_cJetNN_res = 0;
  jet_JECL1FastJet = 0;
  jet_JECFull = 0;
  fatjet_pt = 0;
  fatjet_eta = 0;
  fatjet_phi = 0;
  fatjet_charge = 0;
  fatjet_area = 0;
  fatjet_partonFlavour = 0;
  fatjet_hadronFlavour = 0;
  fatjet_DeepCSV = 0;
  fatjet_DeepCSV_CvsL = 0;
  fatjet_DeepCSV_CvsB = 0;
  fatjet_particleNet_TvsQCD = 0;
  fatjet_particleNet_WvsQCD = 0;
  fatjet_particleNet_ZvsQCD = 0;
  fatjet_particleNet_HbbvsQCD = 0;
  fatjet_particleNet_HccvsQCD = 0;
  fatjet_particleNet_H4qvsQCD = 0;
  fatjet_particleNet_QCD = 0;
  fatjet_particleNetMD_Xbb = 0;
  fatjet_particleNetMD_Xcc = 0;
  fatjet_particleNetMD_Xqq = 0;
  fatjet_particleNetMD_QCD = 0;
  fatjet_tightJetID = 0;
  fatjet_tightLepVetoJetID = 0;
  fatjet_partonPdgId = 0;
  fatjet_vtxNtracks = 0;
  fatjet_m = 0;
  fatjet_energy = 0;
  fatjet_puppi_tau1 = 0;
  fatjet_puppi_tau2 = 0;
  fatjet_puppi_tau3 = 0;
  fatjet_puppi_tau4 = 0;
  fatjet_softdropmass = 0;
  fatjet_chargedHadronEnergyFraction = 0;
  fatjet_neutralHadronEnergyFraction = 0;
  fatjet_neutralEmEnergyFraction = 0;
  fatjet_chargedEmEnergyFraction = 0;
  fatjet_muonEnergyFraction = 0;
  fatjet_chargedMultiplicity = 0;
  fatjet_neutralMultiplicity = 0;
  fatjet_shiftedEnUp = 0;
  fatjet_shiftedEnDown = 0;
  fatjet_smearedRes = 0;
  fatjet_smearedResUp = 0;
  fatjet_smearedResDown = 0;
  fatjet_LSF = 0;
  fatjet_LSFlep_PID = 0;
  fatjet_LSFlep_Pt = 0;
  fatjet_LSFlep_Eta = 0;
  fatjet_LSFlep_Phi = 0;
  electron_MVAIso = 0;
  electron_MVANoIso = 0;
  electron_Energy = 0;
  electron_Energy_Scale_Up = 0;
  electron_Energy_Scale_Down = 0;
  electron_Energy_Smear_Up = 0;
  electron_Energy_Smear_Down = 0;
  electron_eta = 0;
  electron_phi = 0;
  electron_charge = 0;
  electron_gsfpt = 0;
  electron_gsfEta = 0;
  electron_gsfPhi = 0;
  electron_gsfCharge = 0;
  electron_scEta = 0;
  electron_scPhi = 0;
  electron_etaWidth = 0;
  electron_phiWidth = 0;
  electron_dEtaIn = 0;
  electron_dEtaInSeed = 0;
  electron_dPhiIn = 0;
  electron_sigmaIEtaIEta = 0;
  electron_Full5x5_SigmaIEtaIEta = 0;
  electron_e2x5OverE5x5 = 0;
  electron_e1x5OverE5x5 = 0;
  electron_HoverE = 0;
  electron_fbrem = 0;
  electron_eOverP = 0;
  electron_InvEminusInvP = 0;
  electron_dxyVTX = 0;
  electron_dxyerrVTX = 0;
  electron_dzVTX = 0;
  electron_dzerrVTX = 0;
  electron_3DIPVTX = 0;
  electron_3DIPerrVTX = 0;
  electron_dxy = 0;
  electron_sigdxy = 0;
  electron_dz = 0;
  electron_dxyBS = 0;
  electron_dzBS = 0;
  electron_chIso03 = 0;
  electron_nhIso03 = 0;
  electron_phIso03 = 0;
  electron_puChIso03 = 0;
  electron_passConversionVeto = 0;
  electron_isGsfCtfScPixChargeConsistent = 0;
  electron_isGsfScPixChargeConsistent = 0;
  electron_isGsfCtfChargeConsistent = 0;
  electron_mHits = 0;
  electron_ecalDriven = 0;
  electron_r9 = 0;
  electron_l1et = 0;
  electron_scEnergy = 0;
  electron_scPreEnergy = 0;
  electron_scRawEnergy = 0;
  electron_scEt = 0;
  electron_E15 = 0;
  electron_E25 = 0;
  electron_E55 = 0;
  electron_RelPFIso_dBeta = 0;
  electron_RelPFIso_Rho = 0;
  electron_IDBit = 0;
  electron_IDCutBit = 0;
  electron_EnergyUnCorr = 0;
  electron_chMiniIso = 0;
  electron_nhMiniIso = 0;
  electron_phMiniIso = 0;
  electron_puChMiniIso = 0;
  electron_trackIso = 0;
  electron_dr03EcalRecHitSumEt = 0;
  electron_dr03HcalDepth1TowerSumEt = 0;
  electron_dr03HcalTowerSumEt = 0;
  electron_dr03TkSumPt = 0;
  electron_ecalPFClusterIso = 0;
  electron_hcalPFClusterIso = 0;
  electron_pathbits = 0;
  electron_filterbits = 0;
  muon_PfChargedHadronIsoR04 = 0;
  muon_PfNeutralHadronIsoR04 = 0;
  muon_PfGammaIsoR04 = 0;
  muon_PFSumPUIsoR04 = 0;
  muon_PfChargedHadronIsoR03 = 0;
  muon_PfNeutralHadronIsoR03 = 0;
  muon_PfGammaIsoR03 = 0;
  muon_PFSumPUIsoR03 = 0;
  muon_TypeBit = 0;
  muon_IDBit = 0;
  muon_ishighpt = 0;
  muon_ismedium_hip =0;
  muon_ismedium_nohip =0;
  muon_dB = 0;
  muon_phi = 0;
  muon_eta = 0;
  muon_pt = 0;
  muon_mass = 0;
  muon_trkiso = 0;
  muon_hcaliso = 0;
  muon_ecaliso = 0;
  muon_trkisoR05 = 0;
  muon_hcalisoR05 = 0;
  muon_ecalisoR05 = 0;
  muon_charge = 0;
  muon_nChambers = 0;
  muon_matchedstations = 0;
  muon_stationMask = 0;
  muon_nSegments = 0;
  muon_normchi = 0;
  muon_validhits = 0;
  muon_trackerHits = 0;
  muon_pixelHits = 0;
  muon_validmuonhits = 0;
  muon_trackerLayers = 0;
  muon_qoverp = 0;
  muon_theta = 0;
  muon_lambda = 0;
  muon_dxy = 0;
  muon_d0 = 0;
  muon_dsz = 0;
  muon_dz = 0;
  muon_dxyBS = 0;
  muon_dzBS = 0;
  muon_dszBS = 0;
  muon_dxyVTX = 0;
  muon_dxyerrVTX = 0;
  muon_dzVTX = 0;
  muon_dzerrVTX = 0;
  muon_3DIPVTX = 0;
  muon_3DIPerrVTX = 0;
  muon_dszVTX = 0;
  muon_vx = 0;
  muon_vy = 0;
  muon_vz = 0;
  muon_Best_pt = 0;
  muon_Best_ptError = 0;
  muon_Best_eta = 0;
  muon_Best_phi = 0;
  muon_Inner_pt = 0;
  muon_Inner_ptError = 0;
  muon_Inner_eta = 0;
  muon_Inner_phi = 0;
  muon_Outer_pt = 0;
  muon_Outer_ptError = 0;
  muon_Outer_eta = 0;
  muon_Outer_phi = 0;
  muon_GLB_pt = 0;
  muon_GLB_ptError = 0;
  muon_GLB_eta = 0;
  muon_GLB_phi = 0;
  muon_TuneP_pt = 0;
  muon_TuneP_ptError = 0;
  muon_TuneP_eta = 0;
  muon_TuneP_phi = 0;
  muon_TuneP_charge = 0;
  muon_roch_sf = 0;
  muon_roch_sf_up = 0;
  muon_PfChargedHadronMiniIso = 0;
  muon_PfNeutralHadronMiniIso = 0;
  muon_PfGammaMiniIso = 0;
  muon_PFSumPUMiniIso = 0;
  muon_MVA = 0;
  muon_lowptMVA = 0;
  muon_softMVA = 0;
  muon_jetPtRatio = 0;
  muon_jetPtRel = 0;
  muon_simType = 0;
  muon_simExtType = 0;
  muon_simFlavour = 0;
  muon_simHeaviestMotherFlavour = 0;
  muon_simPdgId = 0;
  muon_simMotherPdgId = 0;
  muon_simMatchQuality = 0;
  muon_pathbits = 0;
  muon_filterbits = 0;
  LHE_Px = 0;
  LHE_Py = 0;
  LHE_Pz = 0;
  LHE_E = 0;
  LHE_Status = 0;
  LHE_ID = 0;
  weight_AlphaS = 0;
  weight_PDF = 0;
  weight_Scale = 0;
  weight_PSSyst = 0;
  weight_alpsfact = 0;
  weight_largeptscales = 0;
  weight_q0 = 0;
  weight_sthw2 = 0;
  weight_kHtt = 0;
  gen_phi = 0;
  gen_eta = 0;
  gen_pt = 0;
  gen_mass = 0;
  gen_charge = 0;
  gen_mother_index = 0;
  gen_status = 0;
  gen_PID = 0;
  gen_isPrompt = 0;
  gen_isPromptFinalState = 0;
  gen_isTauDecayProduct = 0;
  gen_isPromptTauDecayProduct = 0;
  gen_isDirectPromptTauDecayProductFinalState = 0;
  gen_isHardProcess = 0;
  gen_isLastCopy = 0;
  gen_isLastCopyBeforeFSR = 0;
  gen_isPromptDecayed = 0;
  gen_isDecayedLeptonHadron = 0;
  gen_fromHardProcessBeforeFSR = 0;
  gen_fromHardProcessDecayed = 0;
  gen_fromHardProcessFinalState = 0;
  gen_isMostlyLikePythia6Status3 = 0;
  photon_Energy = 0;
  photon_EnergyUnCorr = 0;
  photon_eta = 0;
  photon_phi = 0;
  photon_scEta = 0;
  photon_scPhi = 0;
  photon_HoverE = 0;
  photon_hasPixelSeed = 0;
  photon_Full5x5_SigmaIEtaIEta = 0;
  photon_ChIso = 0;
  photon_NhIso = 0;
  photon_PhIso = 0;
  photon_ChIsoWithEA = 0;
  photon_NhIsoWithEA = 0;
  photon_PhIsoWithEA = 0;
  photon_passMVAID_WP80 = 0;
  photon_passMVAID_WP90 = 0;
  photon_passLooseID = 0;
  photon_passMediumID = 0;
  photon_passTightID = 0;
  pfMET_Type1_pt_shifts = 0;
  pfMET_Type1_phi_shifts = 0;
  pfMET_Type1_SumEt_shifts = 0;
  pfMET_Type1_PhiCor_pt_shifts = 0;
  pfMET_Type1_PhiCor_phi_shifts = 0;
  pfMET_Type1_PhiCor_SumEt_shifts = 0;
  PuppiMET_Type1_pt_shifts = 0;
  PuppiMET_Type1_phi_shifts = 0;
  PuppiMET_Type1_SumEt_shifts = 0;
  tau_phi = 0;
  tau_eta = 0;
  tau_pt = 0;
  tau_mass = 0;
  tau_dz = 0;
  tau_dxy = 0;
  tau_decaymode = 0;
  tau_charge = 0;
  tau_IDBit = 0;
  tau_idDecayModeNewDMs = 0;

  fChain->SetBranchAddress("IsData", &IsData, &b_IsData);
  fChain->SetBranchAddress("nTotal", &nTotal, &b_nTotal);
  fChain->SetBranchAddress("run", &run, &b_runNum);
  fChain->SetBranchAddress("event", &event, &b_evtNum);
  fChain->SetBranchAddress("lumi", &lumi, &b_lumiBlock);
  fChain->SetBranchAddress("Rho", &Rho, &b_Rho);
  fChain->SetBranchAddress("RhoNC", &RhoNC, &b_RhoNC);
  fChain->SetBranchAddress("nPV", &nPV, &b_nPV);
  fChain->SetBranchAddress("Flag_goodVertices", &Flag_goodVertices, &b_Flag_goodVertices);
  fChain->SetBranchAddress("Flag_globalSuperTightHalo2016Filter", &Flag_globalSuperTightHalo2016Filter, &b_Flag_globalSuperTightHalo2016Filter);
  fChain->SetBranchAddress("Flag_HBHENoiseFilter", &Flag_HBHENoiseFilter, &b_Flag_HBHENoiseFilter);
  fChain->SetBranchAddress("Flag_HBHENoiseIsoFilter", &Flag_HBHENoiseIsoFilter, &b_Flag_HBHENoiseIsoFilter);
  fChain->SetBranchAddress("Flag_EcalDeadCellTriggerPrimitiveFilter", &Flag_EcalDeadCellTriggerPrimitiveFilter, &b_Flag_EcalDeadCellTriggerPrimitiveFilter);
  fChain->SetBranchAddress("Flag_BadPFMuonFilter", &Flag_BadPFMuonFilter, &b_Flag_BadPFMuonFilter);
  fChain->SetBranchAddress("Flag_BadPFMuonDzFilter", &Flag_BadPFMuonDzFilter, &b_Flag_BadPFMuonDzFilter);
  fChain->SetBranchAddress("Flag_BadChargedCandidateFilter", &Flag_BadChargedCandidateFilter, &b_Flag_BadChargedCandidateFilter);
  fChain->SetBranchAddress("Flag_eeBadScFilter", &Flag_eeBadScFilter, &b_Flag_eeBadScFilter);
  fChain->SetBranchAddress("Flag_ecalBadCalibFilter", &Flag_ecalBadCalibFilter, &b_Flag_ecalBadCalibFilter);
  fChain->SetBranchAddress("PVtrackSize", &PVtrackSize, &b_PVtrackSize);
  fChain->SetBranchAddress("PVchi2", &PVchi2, &b_PVchi2);
  fChain->SetBranchAddress("PVndof", &PVndof, &b_PVndof);
  fChain->SetBranchAddress("PVnormalizedChi2", &PVnormalizedChi2, &b_PVnormalizedChi2);
  fChain->SetBranchAddress("vertex_X", &vertex_X, &b_PVx);
  fChain->SetBranchAddress("vertex_Y", &vertex_Y, &b_PVy);
  fChain->SetBranchAddress("vertex_Z", &vertex_Z, &b_PVz);
  fChain->SetBranchAddress("HLT_TriggerName", &HLT_TriggerName, &b_HLT_TriggerName);
  fChain->SetBranchAddress("jet_pt", &jet_pt, &b_jet_pt);
  fChain->SetBranchAddress("jet_eta", &jet_eta, &b_jet_eta);
  fChain->SetBranchAddress("jet_phi", &jet_phi, &b_jet_phi);
  fChain->SetBranchAddress("jet_charge", &jet_charge, &b_jet_charge);
  fChain->SetBranchAddress("jet_area", &jet_area, &b_jet_area);
  fChain->SetBranchAddress("jet_partonFlavour", &jet_partonFlavour, &b_jet_partonFlavour);
  fChain->SetBranchAddress("jet_hadronFlavour", &jet_hadronFlavour, &b_jet_hadronFlavour);
  fChain->SetBranchAddress("jet_GenHFHadronMatcher_flavour", &jet_GenHFHadronMatcher_flavour, &b_jet_GenHFHadronMatcher_flavour);
  fChain->SetBranchAddress("jet_GenHFHadronMatcher_origin", &jet_GenHFHadronMatcher_origin, &b_jet_GenHFHadronMatcher_origin);
  fChain->SetBranchAddress("jet_DeepCSV", &jet_DeepCSV, &b_jet_DeepCSV);
  fChain->SetBranchAddress("jet_DeepCSV_CvsL", &jet_DeepCSV_CvsL, &b_jet_DeepCSV_CvsL);
  fChain->SetBranchAddress("jet_DeepCSV_CvsB", &jet_DeepCSV_CvsB, &b_jet_DeepCSV_CvsB);
  fChain->SetBranchAddress("jet_DeepFlavour", &jet_DeepJet, &b_jet_DeepJet);
  fChain->SetBranchAddress("jet_DeepFlavour_CvsL", &jet_DeepJet_CvsL, &b_jet_DeepJet_CvsL);
  fChain->SetBranchAddress("jet_DeepFlavour_CvsB", &jet_DeepJet_CvsB, &b_jet_DeepJet_CvsB);
  fChain->SetBranchAddress("jet_chargedHadronEnergyFraction", &jet_chargedHadronEnergyFraction, &b_jet_chargedHadronEnergyFraction);
  fChain->SetBranchAddress("jet_neutralHadronEnergyFraction", &jet_neutralHadronEnergyFraction, &b_jet_neutralHadronEnergyFraction);
  fChain->SetBranchAddress("jet_neutralEmEnergyFraction", &jet_neutralEmEnergyFraction, &b_jet_neutralEmEnergyFraction);
  fChain->SetBranchAddress("jet_chargedEmEnergyFraction", &jet_chargedEmEnergyFraction, &b_jet_chargedEmEnergyFraction);
  fChain->SetBranchAddress("jet_muonEnergyFraction", &jet_muonEnergyFraction, &b_jet_muonEnergyFraction);
  fChain->SetBranchAddress("jet_chargedMultiplicity", &jet_chargedMultiplicity, &b_jet_chargedMultiplicity);
  fChain->SetBranchAddress("jet_neutralMultiplicity", &jet_neutralMultiplicity, &b_jet_neutralMultiplicity);
  fChain->SetBranchAddress("jet_tightJetID", &jet_tightJetID, &b_jet_tightJetID);
  fChain->SetBranchAddress("jet_tightLepVetoJetID", &jet_tightLepVetoJetID, &b_jet_tightLepVetoJetID);
  fChain->SetBranchAddress("jet_partonPdgId", &jet_partonPdgId, &b_jet_partonPdgId);
  fChain->SetBranchAddress("jet_vtxNtracks", &jet_vtxNtracks, &b_jet_vtxNtracks);
  fChain->SetBranchAddress("jet_m", &jet_m, &b_jet_m);
  fChain->SetBranchAddress("jet_energy", &jet_energy, &b_jet_energy);
  fChain->SetBranchAddress("jet_PileupJetId", &jet_PileupJetId, &b_jet_PileupJetId);
  fChain->SetBranchAddress("jet_shiftedEnUp", &jet_shiftedEnUp, &b_jet_shiftedEnUp);
  fChain->SetBranchAddress("jet_shiftedEnDown", &jet_shiftedEnDown, &b_jet_shiftedEnDown);
  fChain->SetBranchAddress("jet_smearedRes", &jet_smearedRes, &b_jet_smearedRes);
  fChain->SetBranchAddress("jet_smearedResUp", &jet_smearedResUp, &b_jet_smearedResUp);
  fChain->SetBranchAddress("jet_smearedResDown", &jet_smearedResDown, &b_jet_smearedResDown);
  fChain->SetBranchAddress("jet_bJetNN_corr", &jet_bJetNN_corr, &b_jet_bJetNN_corr);
  fChain->SetBranchAddress("jet_bJetNN_res", &jet_bJetNN_res, &b_jet_bJetNN_res);
  fChain->SetBranchAddress("jet_cJetNN_corr", &jet_cJetNN_corr, &b_jet_cJetNN_corr);
  fChain->SetBranchAddress("jet_cJetNN_res", &jet_cJetNN_res, &b_jet_cJetNN_res);
  fChain->SetBranchAddress("jet_JECL1FastJet", &jet_JECL1FastJet, &b_jet_JECL1FastJet);
  fChain->SetBranchAddress("jet_JECFull", &jet_JECFull, &b_jet_JECFull);
  fChain->SetBranchAddress("fatjet_pt", &fatjet_pt, &b_fatjet_pt);
  fChain->SetBranchAddress("fatjet_eta", &fatjet_eta, &b_fatjet_eta);
  fChain->SetBranchAddress("fatjet_phi", &fatjet_phi, &b_fatjet_phi);
  fChain->SetBranchAddress("fatjet_charge", &fatjet_charge, &b_fatjet_charge);
  fChain->SetBranchAddress("fatjet_area", &fatjet_area, &b_fatjet_area);
  fChain->SetBranchAddress("fatjet_partonFlavour", &fatjet_partonFlavour, &b_fatjet_partonFlavour);
  fChain->SetBranchAddress("fatjet_hadronFlavour", &fatjet_hadronFlavour, &b_fatjet_hadronFlavour);
  fChain->SetBranchAddress("fatjet_DeepCSV", &fatjet_DeepCSV, &b_fatjet_DeepCSV);
  fChain->SetBranchAddress("fatjet_DeepCSV_CvsL", &fatjet_DeepCSV_CvsL, &b_fatjet_DeepCSV_CvsL);
  fChain->SetBranchAddress("fatjet_DeepCSV_CvsB", &fatjet_DeepCSV_CvsB, &b_fatjet_DeepCSV_CvsB);
  fChain->SetBranchAddress("fatjet_particleNet_TvsQCD", &fatjet_particleNet_TvsQCD, &b_fatjet_particleNet_TvsQCD);
  fChain->SetBranchAddress("fatjet_particleNet_WvsQCD", &fatjet_particleNet_WvsQCD, &b_fatjet_particleNet_WvsQCD);
  fChain->SetBranchAddress("fatjet_particleNet_ZvsQCD", &fatjet_particleNet_ZvsQCD, &b_fatjet_particleNet_ZvsQCD);
  fChain->SetBranchAddress("fatjet_particleNet_HbbvsQCD", &fatjet_particleNet_HbbvsQCD, &b_fatjet_particleNet_HbbvsQCD);
  fChain->SetBranchAddress("fatjet_particleNet_HccvsQCD", &fatjet_particleNet_HccvsQCD, &b_fatjet_particleNet_HccvsQCD);
  fChain->SetBranchAddress("fatjet_particleNet_H4qvsQCD", &fatjet_particleNet_H4qvsQCD, &b_fatjet_particleNet_H4qvsQCD);
  fChain->SetBranchAddress("fatjet_particleNet_QCD", &fatjet_particleNet_QCD, &b_fatjet_particleNet_QCD);
  fChain->SetBranchAddress("fatjet_particleNetMD_Xbb", &fatjet_particleNetMD_Xbb, &b_fatjet_particleNetMD_Xbb);
  fChain->SetBranchAddress("fatjet_particleNetMD_Xcc", &fatjet_particleNetMD_Xcc, &b_fatjet_particleNetMD_Xcc);
  fChain->SetBranchAddress("fatjet_particleNetMD_Xqq", &fatjet_particleNetMD_Xqq, &b_fatjet_particleNetMD_Xqq);
  fChain->SetBranchAddress("fatjet_particleNetMD_QCD", &fatjet_particleNetMD_QCD, &b_fatjet_particleNetMD_QCD);
  fChain->SetBranchAddress("fatjet_tightJetID", &fatjet_tightJetID, &b_fatjet_tightJetID);
  fChain->SetBranchAddress("fatjet_tightLepVetoJetID", &fatjet_tightLepVetoJetID, &b_fatjet_tightLepVetoJetID);
  fChain->SetBranchAddress("fatjet_partonPdgId", &fatjet_partonPdgId, &b_fatjet_partonPdgId);
  fChain->SetBranchAddress("fatjet_vtxNtracks", &fatjet_vtxNtracks, &b_fatjet_vtxNtracks);
  fChain->SetBranchAddress("fatjet_m", &fatjet_m, &b_fatjet_m);
  fChain->SetBranchAddress("fatjet_energy", &fatjet_energy, &b_fatjet_energy);
  fChain->SetBranchAddress("fatjet_puppi_tau1", &fatjet_puppi_tau1, &b_fatjet_puppi_tau1);
  fChain->SetBranchAddress("fatjet_puppi_tau2", &fatjet_puppi_tau2, &b_fatjet_puppi_tau2);
  fChain->SetBranchAddress("fatjet_puppi_tau3", &fatjet_puppi_tau3, &b_fatjet_puppi_tau3);
  fChain->SetBranchAddress("fatjet_puppi_tau4", &fatjet_puppi_tau4, &b_fatjet_puppi_tau4);
  fChain->SetBranchAddress("fatjet_softdropmass", &fatjet_softdropmass, &b_fatjet_softdropmass);
  fChain->SetBranchAddress("fatjet_chargedHadronEnergyFraction", &fatjet_chargedHadronEnergyFraction, &b_fatjet_chargedHadronEnergyFraction);
  fChain->SetBranchAddress("fatjet_neutralHadronEnergyFraction", &fatjet_neutralHadronEnergyFraction, &b_fatjet_neutralHadronEnergyFraction);
  fChain->SetBranchAddress("fatjet_neutralEmEnergyFraction", &fatjet_neutralEmEnergyFraction, &b_fatjet_neutralEmEnergyFraction);
  fChain->SetBranchAddress("fatjet_chargedEmEnergyFraction", &fatjet_chargedEmEnergyFraction, &b_fatjet_chargedEmEnergyFraction);
  fChain->SetBranchAddress("fatjet_muonEnergyFraction", &fatjet_muonEnergyFraction, &b_fatjet_muonEnergyFraction);
  fChain->SetBranchAddress("fatjet_chargedMultiplicity", &fatjet_chargedMultiplicity, &b_fatjet_chargedMultiplicity);
  fChain->SetBranchAddress("fatjet_neutralMultiplicity", &fatjet_neutralMultiplicity, &b_fatjet_neutralMultiplicity);
  fChain->SetBranchAddress("fatjet_shiftedEnUp", &fatjet_shiftedEnUp, &b_fatjet_shiftedEnUp);
  fChain->SetBranchAddress("fatjet_shiftedEnDown", &fatjet_shiftedEnDown, &b_fatjet_shiftedEnDown);
  fChain->SetBranchAddress("fatjet_smearedRes", &fatjet_smearedRes, &b_fatjet_smearedRes);
  fChain->SetBranchAddress("fatjet_smearedResUp", &fatjet_smearedResUp, &b_fatjet_smearedResUp);
  fChain->SetBranchAddress("fatjet_smearedResDown", &fatjet_smearedResDown, &b_fatjet_smearedResDown);
  fChain->SetBranchAddress("fatjet_LSF", &fatjet_LSF, &b_fatjet_LSF);
  fChain->SetBranchAddress("fatjet_LSFlep_PID", &fatjet_LSFlep_PID, &b_fatjet_LSFlep_PID);
  fChain->SetBranchAddress("fatjet_LSFlep_Pt", &fatjet_LSFlep_Pt, &b_fatjet_LSFlep_Pt);
  fChain->SetBranchAddress("fatjet_LSFlep_Eta", &fatjet_LSFlep_Eta, &b_fatjet_LSFlep_Eta);
  fChain->SetBranchAddress("fatjet_LSFlep_Phi", &fatjet_LSFlep_Phi, &b_fatjet_LSFlep_Phi);
  fChain->SetBranchAddress("electron_MVAIso", &electron_MVAIso, &b_electron_MVAIso);
  fChain->SetBranchAddress("electron_MVANoIso", &electron_MVANoIso, &b_electron_MVANoIso);
  fChain->SetBranchAddress("electron_Energy", &electron_Energy, &b_electron_Energy);
  fChain->SetBranchAddress("electron_Energy_Scale_Up", &electron_Energy_Scale_Up, &b_electron_Energy_Scale_Up);
  fChain->SetBranchAddress("electron_Energy_Scale_Down", &electron_Energy_Scale_Down, &b_electron_Energy_Scale_Down);
  fChain->SetBranchAddress("electron_Energy_Smear_Up", &electron_Energy_Smear_Up, &b_electron_Energy_Smear_Up);
  fChain->SetBranchAddress("electron_Energy_Smear_Down", &electron_Energy_Smear_Down, &b_electron_Energy_Smear_Down);
  fChain->SetBranchAddress("electron_eta", &electron_eta, &b_electron_eta);
  fChain->SetBranchAddress("electron_phi", &electron_phi, &b_electron_phi);
  fChain->SetBranchAddress("electron_charge", &electron_charge, &b_electron_charge);
  fChain->SetBranchAddress("electron_gsfpt", &electron_gsfpt, &b_electron_gsfpt);
  fChain->SetBranchAddress("electron_gsfEta", &electron_gsfEta, &b_electron_gsfEta);
  fChain->SetBranchAddress("electron_gsfPhi", &electron_gsfPhi, &b_electron_gsfPhi);
  fChain->SetBranchAddress("electron_gsfCharge", &electron_gsfCharge, &b_electron_gsfCharge);
  fChain->SetBranchAddress("electron_scEta", &electron_scEta, &b_electron_scEta);
  fChain->SetBranchAddress("electron_scPhi", &electron_scPhi, &b_electron_scPhi);
  fChain->SetBranchAddress("electron_etaWidth", &electron_etaWidth, &b_electron_etaWidth);
  fChain->SetBranchAddress("electron_phiWidth", &electron_phiWidth, &b_electron_phiWidth);
  fChain->SetBranchAddress("electron_dEtaIn", &electron_dEtaIn, &b_electron_dEtaIn);
  fChain->SetBranchAddress("electron_dEtaInSeed", &electron_dEtaInSeed, &b_electron_dEtaInSeed);
  fChain->SetBranchAddress("electron_dPhiIn", &electron_dPhiIn, &b_electron_dPhiIn);
  fChain->SetBranchAddress("electron_sigmaIEtaIEta", &electron_sigmaIEtaIEta, &b_electron_sigmaIEtaIEta);
  fChain->SetBranchAddress("electron_Full5x5_SigmaIEtaIEta", &electron_Full5x5_SigmaIEtaIEta, &b_electron_Full5x5_SigmaIEtaIEta);
  fChain->SetBranchAddress("electron_e2x5OverE5x5", &electron_e2x5OverE5x5, &b_electron_e2x5OverE5x5);
  fChain->SetBranchAddress("electron_e1x5OverE5x5", &electron_e1x5OverE5x5, &b_electron_e1x5OverE5x5);
  fChain->SetBranchAddress("electron_HoverE", &electron_HoverE, &b_electron_HoverE);
  fChain->SetBranchAddress("electron_fbrem", &electron_fbrem, &b_electron_fbrem);
  fChain->SetBranchAddress("electron_eOverP", &electron_eOverP, &b_electron_eOverP);
  fChain->SetBranchAddress("electron_InvEminusInvP", &electron_InvEminusInvP, &b_electron_InvEminusInvP);
  fChain->SetBranchAddress("electron_dxyVTX", &electron_dxyVTX, &b_electron_dxyVTX);
  fChain->SetBranchAddress("electron_dxyerrVTX", &electron_dxyerrVTX, &b_electron_dxyerrVTX);
  fChain->SetBranchAddress("electron_dzVTX", &electron_dzVTX, &b_electron_dzVTX);
  fChain->SetBranchAddress("electron_dzerrVTX", &electron_dzerrVTX, &b_electron_dzerrVTX);
  fChain->SetBranchAddress("electron_3DIPVTX", &electron_3DIPVTX, &b_electron_3DIPVTX);
  fChain->SetBranchAddress("electron_3DIPerrVTX", &electron_3DIPerrVTX, &b_electron_3DIPerrVTX);
  fChain->SetBranchAddress("electron_dxy", &electron_dxy, &b_electron_dxy);
  fChain->SetBranchAddress("electron_sigdxy", &electron_sigdxy, &b_electron_sigdxy);
  fChain->SetBranchAddress("electron_dz", &electron_dz, &b_electron_dz);
  fChain->SetBranchAddress("electron_dxyBS", &electron_dxyBS, &b_electron_dxyBS);
  fChain->SetBranchAddress("electron_dzBS", &electron_dzBS, &b_electron_dzBS);
  fChain->SetBranchAddress("electron_chIso03", &electron_chIso03, &b_electron_chIso03);
  fChain->SetBranchAddress("electron_nhIso03", &electron_nhIso03, &b_electron_nhIso03);
  fChain->SetBranchAddress("electron_phIso03", &electron_phIso03, &b_electron_phIso03);
  fChain->SetBranchAddress("electron_puChIso03", &electron_puChIso03, &b_electron_puChIso03);
  fChain->SetBranchAddress("electron_passConversionVeto", &electron_passConversionVeto, &b_electron_passConversionVeto);
  fChain->SetBranchAddress("electron_isGsfCtfScPixChargeConsistent", &electron_isGsfCtfScPixChargeConsistent, &b_electron_isGsfCtfScPixChargeConsistent);
  fChain->SetBranchAddress("electron_isGsfScPixChargeConsistent", &electron_isGsfScPixChargeConsistent, &b_electron_isGsfScPixChargeConsistent);
  fChain->SetBranchAddress("electron_isGsfCtfChargeConsistent", &electron_isGsfCtfChargeConsistent, &b_electron_isGsfCtfChargeConsistent);
  fChain->SetBranchAddress("electron_mHits", &electron_mHits, &b_electron_mHits);
  fChain->SetBranchAddress("electron_ecalDriven", &electron_ecalDriven, &b_electron_ecalDriven);
  fChain->SetBranchAddress("electron_r9", &electron_r9, &b_electron_r9);
  fChain->SetBranchAddress("electron_l1et", &electron_l1et, &b_electron_l1et);
  fChain->SetBranchAddress("electron_scEnergy", &electron_scEnergy, &b_electron_scEnergy);
  fChain->SetBranchAddress("electron_scPreEnergy", &electron_scPreEnergy, &b_electron_scPreEnergy);
  fChain->SetBranchAddress("electron_scRawEnergy", &electron_scRawEnergy, &b_electron_scRawEnergy);
  fChain->SetBranchAddress("electron_scEt", &electron_scEt, &b_electron_scEt);
  fChain->SetBranchAddress("electron_E15", &electron_E15, &b_electron_E15);
  fChain->SetBranchAddress("electron_E25", &electron_E25, &b_electron_E25);
  fChain->SetBranchAddress("electron_E55", &electron_E55, &b_electron_E55);
  fChain->SetBranchAddress("electron_RelPFIso_dBeta", &electron_RelPFIso_dBeta, &b_electron_RelPFIso_dBeta);
  fChain->SetBranchAddress("electron_RelPFIso_Rho", &electron_RelPFIso_Rho, &b_electron_RelPFIso_Rho);
  fChain->SetBranchAddress("electron_IDBit", &electron_IDBit, &b_electron_IDBit);
  fChain->SetBranchAddress("electron_IDCutBit", &electron_IDCutBit, &b_electron_IDCutBit);
  fChain->SetBranchAddress("electron_EnergyUnCorr", &electron_EnergyUnCorr, &b_electron_EnergyUnCorr);
  fChain->SetBranchAddress("electron_chMiniIso", &electron_chMiniIso, &b_electron_chMiniIso);
  fChain->SetBranchAddress("electron_nhMiniIso", &electron_nhMiniIso, &b_electron_nhMiniIso);
  fChain->SetBranchAddress("electron_phMiniIso", &electron_phMiniIso, &b_electron_phMiniIso);
  fChain->SetBranchAddress("electron_puChMiniIso", &electron_puChMiniIso, &b_electron_puChMiniIso);
  fChain->SetBranchAddress("electron_trackIso", &electron_trackIso, &b_electron_trackIso);
  fChain->SetBranchAddress("electron_dr03EcalRecHitSumEt", &electron_dr03EcalRecHitSumEt, &b_electron_dr03EcalRecHitSumEt);
  fChain->SetBranchAddress("electron_dr03HcalDepth1TowerSumEt", &electron_dr03HcalDepth1TowerSumEt, &b_electron_dr03HcalDepth1TowerSumEt);
  fChain->SetBranchAddress("electron_dr03HcalTowerSumEt", &electron_dr03HcalTowerSumEt, &b_electron_dr03HcalTowerSumEt);
  fChain->SetBranchAddress("electron_dr03TkSumPt", &electron_dr03TkSumPt, &b_electron_dr03TkSumPt);
  fChain->SetBranchAddress("electron_ecalPFClusterIso", &electron_ecalPFClusterIso, &b_electron_ecalPFClusterIso);
  fChain->SetBranchAddress("electron_hcalPFClusterIso", &electron_hcalPFClusterIso, &b_electron_hcalPFClusterIso);
  fChain->SetBranchAddress("electron_pathbits", &electron_pathbits, &b_electron_pathbits);
  fChain->SetBranchAddress("electron_filterbits", &electron_filterbits, &b_electron_filterbits);
  fChain->SetBranchAddress("muon_PfChargedHadronIsoR04", &muon_PfChargedHadronIsoR04, &b_muon_PfChargedHadronIsoR04);
  fChain->SetBranchAddress("muon_PfNeutralHadronIsoR04", &muon_PfNeutralHadronIsoR04, &b_muon_PfNeutralHadronIsoR04);
  fChain->SetBranchAddress("muon_PfGammaIsoR04", &muon_PfGammaIsoR04, &b_muon_PfGammaIsoR04);
  fChain->SetBranchAddress("muon_PFSumPUIsoR04", &muon_PFSumPUIsoR04, &b_muon_PFSumPUIsoR04);
  fChain->SetBranchAddress("muon_PfChargedHadronIsoR03", &muon_PfChargedHadronIsoR03, &b_muon_PfChargedHadronIsoR03);
  fChain->SetBranchAddress("muon_PfNeutralHadronIsoR03", &muon_PfNeutralHadronIsoR03, &b_muon_PfNeutralHadronIsoR03);
  fChain->SetBranchAddress("muon_PfGammaIsoR03", &muon_PfGammaIsoR03, &b_muon_PfGammaIsoR03);
  fChain->SetBranchAddress("muon_PFSumPUIsoR03", &muon_PFSumPUIsoR03, &b_muon_PFSumPUIsoR03);
  fChain->SetBranchAddress("muon_TypeBit", &muon_TypeBit, &b_muon_TypeBit);
  fChain->SetBranchAddress("muon_IDBit", &muon_IDBit, &b_muon_IDBit);
  fChain->SetBranchAddress("muon_ishighpt", &muon_ishighpt, &b_muon_ishighpt);
  fChain->SetBranchAddress("muon_ismedium_hip", &muon_ismedium_hip, &b_muon_ismedium_hip);
  fChain->SetBranchAddress("muon_ismedium_nohip", &muon_ismedium_nohip, &b_muon_ismedium_nohip);
  fChain->SetBranchAddress("muon_dB", &muon_dB, &b_muon_dB);
  fChain->SetBranchAddress("muon_phi", &muon_phi, &b_muon_phi);
  fChain->SetBranchAddress("muon_eta", &muon_eta, &b_muon_eta);
  fChain->SetBranchAddress("muon_pt", &muon_pt, &b_muon_pt);
  fChain->SetBranchAddress("muon_mass", &muon_mass, &b_muon_mass);
  fChain->SetBranchAddress("muon_trkiso", &muon_trkiso, &b_muon_trkiso);
  fChain->SetBranchAddress("muon_hcaliso", &muon_hcaliso, &b_muon_hcaliso);
  fChain->SetBranchAddress("muon_ecaliso", &muon_ecaliso, &b_muon_ecaliso);
  fChain->SetBranchAddress("muon_trkisoR05", &muon_trkisoR05, &b_muon_trkisoR05);
  fChain->SetBranchAddress("muon_hcalisoR05", &muon_hcalisoR05, &b_muon_hcalisoR05);
  fChain->SetBranchAddress("muon_ecalisoR05", &muon_ecalisoR05, &b_muon_ecalisoR05);
  fChain->SetBranchAddress("muon_charge", &muon_charge, &b_muon_charge);
  fChain->SetBranchAddress("muon_nChambers", &muon_nChambers, &b_muon_nChambers);
  fChain->SetBranchAddress("muon_matchedstations", &muon_matchedstations, &b_muon_matchedstations);
  fChain->SetBranchAddress("muon_stationMask", &muon_stationMask, &b_muon_stationMask);
  fChain->SetBranchAddress("muon_nSegments", &muon_nSegments, &b_muon_nSegments);
  fChain->SetBranchAddress("muon_normchi", &muon_normchi, &b_muon_normchi);
  fChain->SetBranchAddress("muon_validhits", &muon_validhits, &b_muon_validhits);
  fChain->SetBranchAddress("muon_trackerHits", &muon_trackerHits, &b_muon_trackerHits);
  fChain->SetBranchAddress("muon_pixelHits", &muon_pixelHits, &b_muon_pixelHits);
  fChain->SetBranchAddress("muon_validmuonhits", &muon_validmuonhits, &b_muon_validmuonhits);
  fChain->SetBranchAddress("muon_trackerLayers", &muon_trackerLayers, &b_muon_trackerLayers);
  fChain->SetBranchAddress("muon_qoverp", &muon_qoverp, &b_muon_qoverp);
  fChain->SetBranchAddress("muon_theta", &muon_theta, &b_muon_theta);
  fChain->SetBranchAddress("muon_lambda", &muon_lambda, &b_muon_lambda);
  fChain->SetBranchAddress("muon_dxy", &muon_dxy, &b_muon_dxy);
  fChain->SetBranchAddress("muon_d0", &muon_d0, &b_muon_d0);
  fChain->SetBranchAddress("muon_dsz", &muon_dsz, &b_muon_dsz);
  fChain->SetBranchAddress("muon_dz", &muon_dz, &b_muon_dz);
  fChain->SetBranchAddress("muon_dxyBS", &muon_dxyBS, &b_muon_dxyBS);
  fChain->SetBranchAddress("muon_dzBS", &muon_dzBS, &b_muon_dzBS);
  fChain->SetBranchAddress("muon_dszBS", &muon_dszBS, &b_muon_dszBS);
  fChain->SetBranchAddress("muon_dxyVTX", &muon_dxyVTX, &b_muon_dxyVTX);
  fChain->SetBranchAddress("muon_dxyerrVTX", &muon_dxyerrVTX, &b_muon_dxyerrVTX);
  fChain->SetBranchAddress("muon_dzVTX", &muon_dzVTX, &b_muon_dzVTX);
  fChain->SetBranchAddress("muon_dzerrVTX", &muon_dzerrVTX, &b_muon_dzerrVTX);
  fChain->SetBranchAddress("muon_3DIPVTX", &muon_3DIPVTX, &b_muon_3DIPVTX);
  fChain->SetBranchAddress("muon_3DIPerrVTX", &muon_3DIPerrVTX, &b_muon_3DIPerrVTX);
  fChain->SetBranchAddress("muon_dszVTX", &muon_dszVTX, &b_muon_dszVTX);
  fChain->SetBranchAddress("muon_vx", &muon_vx, &b_muon_vx);
  fChain->SetBranchAddress("muon_vy", &muon_vy, &b_muon_vy);
  fChain->SetBranchAddress("muon_vz", &muon_vz, &b_muon_vz);
  fChain->SetBranchAddress("muon_Best_pt", &muon_Best_pt, &b_muon_Best_pt);
  fChain->SetBranchAddress("muon_Best_ptError", &muon_Best_ptError, &b_muon_Best_ptError);
  fChain->SetBranchAddress("muon_Best_eta", &muon_Best_eta, &b_muon_Best_eta);
  fChain->SetBranchAddress("muon_Best_phi", &muon_Best_phi, &b_muon_Best_phi);
  fChain->SetBranchAddress("muon_Inner_pt", &muon_Inner_pt, &b_muon_Inner_pt);
  fChain->SetBranchAddress("muon_Inner_ptError", &muon_Inner_ptError, &b_muon_Inner_ptError);
  fChain->SetBranchAddress("muon_Inner_eta", &muon_Inner_eta, &b_muon_Inner_eta);
  fChain->SetBranchAddress("muon_Inner_phi", &muon_Inner_phi, &b_muon_Inner_phi);
  fChain->SetBranchAddress("muon_Outer_pt", &muon_Outer_pt, &b_muon_Outer_pt);
  fChain->SetBranchAddress("muon_Outer_ptError", &muon_Outer_ptError, &b_muon_Outer_ptError);
  fChain->SetBranchAddress("muon_Outer_eta", &muon_Outer_eta, &b_muon_Outer_eta);
  fChain->SetBranchAddress("muon_Outer_phi", &muon_Outer_phi, &b_muon_Outer_phi);
  fChain->SetBranchAddress("muon_GLB_pt", &muon_GLB_pt, &b_muon_GLB_pt);
  fChain->SetBranchAddress("muon_GLB_ptError", &muon_GLB_ptError, &b_muon_GLB_ptError);
  fChain->SetBranchAddress("muon_GLB_eta", &muon_GLB_eta, &b_muon_GLB_eta);
  fChain->SetBranchAddress("muon_GLB_phi", &muon_GLB_phi, &b_muon_GLB_phi);
  fChain->SetBranchAddress("muon_TuneP_pt", &muon_TuneP_pt, &b_muon_TuneP_pt);
  fChain->SetBranchAddress("muon_TuneP_ptError", &muon_TuneP_ptError, &b_muon_TuneP_ptError);
  fChain->SetBranchAddress("muon_TuneP_eta", &muon_TuneP_eta, &b_muon_TuneP_eta);
  fChain->SetBranchAddress("muon_TuneP_phi", &muon_TuneP_phi, &b_muon_TuneP_phi);
  fChain->SetBranchAddress("muon_TuneP_charge", &muon_TuneP_charge, &b_muon_TuneP_charge);
  fChain->SetBranchAddress("muon_roch_sf", &muon_roch_sf, &b_muon_roch_sf);
  fChain->SetBranchAddress("muon_roch_sf_up", &muon_roch_sf_up, &b_muon_roch_sf_up);
  fChain->SetBranchAddress("muon_PfChargedHadronMiniIso", &muon_PfChargedHadronMiniIso, &b_muon_PfChargedHadronMiniIso);
  fChain->SetBranchAddress("muon_PfNeutralHadronMiniIso", &muon_PfNeutralHadronMiniIso, &b_muon_PfNeutralHadronMiniIso);
  fChain->SetBranchAddress("muon_PfGammaMiniIso", &muon_PfGammaMiniIso, &b_muon_PfGammaMiniIso);
  fChain->SetBranchAddress("muon_PFSumPUMiniIso", &muon_PFSumPUMiniIso, &b_muon_PFSumPUMiniIso);
  fChain->SetBranchAddress("muon_MVA", &muon_MVA, &b_muon_MVA);
  fChain->SetBranchAddress("muon_lowptMVA", &muon_lowptMVA, &b_muon_lowptMVA);
  fChain->SetBranchAddress("muon_softMVA", &muon_softMVA, &b_muon_softMVA);
  fChain->SetBranchAddress("muon_jetPtRatio", &muon_jetPtRatio, &b_muon_jetPtRatio);
  fChain->SetBranchAddress("muon_jetPtRel", &muon_jetPtRel, &b_muon_jetPtRel);
  fChain->SetBranchAddress("muon_simType", &muon_simType, &b_muon_simType);
  fChain->SetBranchAddress("muon_simExtType", &muon_simExtType, &b_muon_simExtType);
  fChain->SetBranchAddress("muon_simFlavour", &muon_simFlavour, &b_muon_simFlavour);
  fChain->SetBranchAddress("muon_simHeaviestMotherFlavour", &muon_simHeaviestMotherFlavour, &b_muon_simHeaviestMotherFlavour);
  fChain->SetBranchAddress("muon_simPdgId", &muon_simPdgId, &b_muon_simPdgId);
  fChain->SetBranchAddress("muon_simMotherPdgId", &muon_simMotherPdgId, &b_muon_simMotherPdgId);
  fChain->SetBranchAddress("muon_simMatchQuality", &muon_simMatchQuality, &b_muon_simMatchQuality);
  fChain->SetBranchAddress("muon_pathbits", &muon_pathbits, &b_muon_pathbits);
  fChain->SetBranchAddress("muon_filterbits", &muon_filterbits, &b_muon_filterbits);
  if(!IsDATA){
  fChain->SetBranchAddress("L1PrefireReweight_Central", &L1PrefireReweight_Central, &b_L1PrefireReweight_Central);
  fChain->SetBranchAddress("L1PrefireReweight_Up", &L1PrefireReweight_Up, &b_L1PrefireReweight_Up);
  fChain->SetBranchAddress("L1PrefireReweight_Down", &L1PrefireReweight_Down, &b_L1PrefireReweight_Down);
  fChain->SetBranchAddress("LHE_Px", &LHE_Px, &b_LHE_Px);
  fChain->SetBranchAddress("LHE_Py", &LHE_Py, &b_LHE_Py);
  fChain->SetBranchAddress("LHE_Pz", &LHE_Pz, &b_LHE_Pz);
  fChain->SetBranchAddress("LHE_E", &LHE_E, &b_LHE_E);
  fChain->SetBranchAddress("LHE_Status", &LHE_Status, &b_LHE_Status);
  fChain->SetBranchAddress("LHE_ID", &LHE_ID, &b_LHE_ID);
  if(fChain->GetBranch("weight_AlphaS")) fChain->SetBranchAddress("weight_AlphaS", &weight_AlphaS, &b_weight_AlphaS);
  if(fChain->GetBranch("weight_PDF")) fChain->SetBranchAddress("weight_PDF", &weight_PDF, &b_weight_PDF);
  if(fChain->GetBranch("weight_Scale")) fChain->SetBranchAddress("weight_Scale", &weight_Scale, &b_weight_Scale);
  if(fChain->GetBranch("weight_PSSyst")) fChain->SetBranchAddress("weight_PSSyst", &weight_PSSyst, &b_weight_PSSyst);
  if(fChain->GetBranch("weight_alpsfact")) fChain->SetBranchAddress("weight_alpsfact", &weight_alpsfact, &b_weight_alpsfact);
  if(fChain->GetBranch("weight_largeptscales")) fChain->SetBranchAddress("weight_largeptscales", &weight_largeptscales, &b_weight_largeptscales);
  if(fChain->GetBranch("weight_q0")) fChain->SetBranchAddress("weight_q0", &weight_q0, &b_weight_q0);
  if(fChain->GetBranch("weight_sthw2")) fChain->SetBranchAddress("weight_sthw2", &weight_sthw2, &b_weight_sthw2);
  if(fChain->GetBranch("weight_kHtt")) fChain->SetBranchAddress("weight_kHtt", &weight_kHtt, &b_weight_kHtt);
  fChain->SetBranchAddress("gen_phi", &gen_phi, &b_gen_phi);
  fChain->SetBranchAddress("gen_eta", &gen_eta, &b_gen_eta);
  fChain->SetBranchAddress("gen_pt", &gen_pt, &b_gen_pt);
  fChain->SetBranchAddress("gen_mass", &gen_mass, &b_gen_mass);
  fChain->SetBranchAddress("gen_charge", &gen_charge, &b_gen_charge);
  fChain->SetBranchAddress("gen_mother_index", &gen_mother_index, &b_gen_mother_index);
  fChain->SetBranchAddress("gen_status", &gen_status, &b_gen_status);
  fChain->SetBranchAddress("gen_PID", &gen_PID, &b_gen_PID);
  fChain->SetBranchAddress("gen_isPrompt", &gen_isPrompt, &b_gen_isPrompt);
  fChain->SetBranchAddress("gen_isPromptFinalState", &gen_isPromptFinalState, &b_gen_isPromptFinalState);
  fChain->SetBranchAddress("gen_isTauDecayProduct", &gen_isTauDecayProduct, &b_gen_isTauDecayProduct);
  fChain->SetBranchAddress("gen_isPromptTauDecayProduct", &gen_isPromptTauDecayProduct, &b_gen_isPromptTauDecayProduct);
  fChain->SetBranchAddress("gen_isDirectPromptTauDecayProductFinalState", &gen_isDirectPromptTauDecayProductFinalState, &b_gen_isDirectPromptTauDecayProductFinalState);
  fChain->SetBranchAddress("gen_isHardProcess", &gen_isHardProcess, &b_gen_isHardProcess);
  fChain->SetBranchAddress("gen_isLastCopy", &gen_isLastCopy, &b_gen_isLastCopy);
  fChain->SetBranchAddress("gen_isLastCopyBeforeFSR", &gen_isLastCopyBeforeFSR, &b_gen_isLastCopyBeforeFSR);
  fChain->SetBranchAddress("gen_isPromptDecayed", &gen_isPromptDecayed, &b_gen_isPromptDecayed);
  fChain->SetBranchAddress("gen_isDecayedLeptonHadron", &gen_isDecayedLeptonHadron, &b_gen_isDecayedLeptonHadron);
  fChain->SetBranchAddress("gen_fromHardProcessBeforeFSR", &gen_fromHardProcessBeforeFSR, &b_gen_fromHardProcessBeforeFSR);
  fChain->SetBranchAddress("gen_fromHardProcessDecayed", &gen_fromHardProcessDecayed, &b_gen_fromHardProcessDecayed);
  fChain->SetBranchAddress("gen_fromHardProcessFinalState", &gen_fromHardProcessFinalState, &b_gen_fromHardProcessFinalState);
  fChain->SetBranchAddress("gen_isMostlyLikePythia6Status3", &gen_isMostlyLikePythia6Status3, &b_gen_isMostlyLikePythia6Status3);
  fChain->SetBranchAddress("gen_weight", &gen_weight, &b_gen_weight);
  fChain->SetBranchAddress("genWeight_Q", &genWeight_Q, &b_genWeight_Q);
  fChain->SetBranchAddress("genWeight_X1", &genWeight_X1, &b_genWeight_X1);
  fChain->SetBranchAddress("genWeight_X2", &genWeight_X2, &b_genWeight_X2);
  fChain->SetBranchAddress("genWeight_id1", &genWeight_id1, &b_genWeight_id1);
  fChain->SetBranchAddress("genWeight_id2", &genWeight_id2, &b_genWeight_id2);
  fChain->SetBranchAddress("genWeight_alphaQCD", &genWeight_alphaQCD, &b_genWeight_alphaQCD);
  fChain->SetBranchAddress("genWeight_alphaQED", &genWeight_alphaQED, &b_genWeight_alphaQED);
  }
  fChain->SetBranchAddress("photon_Energy", &photon_Energy, &b_photon_Energy);
  fChain->SetBranchAddress("photon_EnergyUnCorr", &photon_EnergyUnCorr, &b_photon_EnergyUnCorr);
  fChain->SetBranchAddress("photon_eta", &photon_eta, &b_photon_eta);
  fChain->SetBranchAddress("photon_phi", &photon_phi, &b_photon_phi);
  fChain->SetBranchAddress("photon_scEta", &photon_scEta, &b_photon_scEta);
  fChain->SetBranchAddress("photon_scPhi", &photon_scPhi, &b_photon_scPhi);
  fChain->SetBranchAddress("photon_HoverE", &photon_HoverE, &b_photon_HoverE);
  fChain->SetBranchAddress("photon_hasPixelSeed", &photon_hasPixelSeed, &b_photon_hasPixelSeed);
  fChain->SetBranchAddress("photon_Full5x5_SigmaIEtaIEta", &photon_Full5x5_SigmaIEtaIEta, &b_photon_Full5x5_SigmaIEtaIEta);
  fChain->SetBranchAddress("photon_ChIso", &photon_ChIso, &b_photon_ChIso);
  fChain->SetBranchAddress("photon_NhIso", &photon_NhIso, &b_photon_NhIso);
  fChain->SetBranchAddress("photon_PhIso", &photon_PhIso, &b_photon_PhIso);
  fChain->SetBranchAddress("photon_ChIsoWithEA", &photon_ChIsoWithEA, &b_photon_ChIsoWithEA);
  fChain->SetBranchAddress("photon_NhIsoWithEA", &photon_NhIsoWithEA, &b_photon_NhIsoWithEA);
  fChain->SetBranchAddress("photon_PhIsoWithEA", &photon_PhIsoWithEA, &b_photon_PhIsoWithEA);
  fChain->SetBranchAddress("photon_passMVAID_WP80", &photon_passMVAID_WP80, &b_photon_passMVAID_WP80);
  fChain->SetBranchAddress("photon_passMVAID_WP90", &photon_passMVAID_WP90, &b_photon_passMVAID_WP90);
  fChain->SetBranchAddress("photon_passLooseID", &photon_passLooseID, &b_photon_passLooseID);
  fChain->SetBranchAddress("photon_passMediumID", &photon_passMediumID, &b_photon_passMediumID);
  fChain->SetBranchAddress("photon_passTightID", &photon_passTightID, &b_photon_passTightID);
  fChain->SetBranchAddress("nPileUp", &nPileUp, &b_nPileUp);
  fChain->SetBranchAddress("pfMET_pt", &pfMET_pt, &b_pfMET_pt);
  fChain->SetBranchAddress("pfMET_phi", &pfMET_phi, &b_pfMET_phi);
  fChain->SetBranchAddress("pfMET_SumEt", &pfMET_SumEt, &b_pfMET_SumEt);
  fChain->SetBranchAddress("pfMET_Type1_pt", &pfMET_Type1_pt, &b_pfMET_Type1_pt);
  fChain->SetBranchAddress("pfMET_Type1_phi", &pfMET_Type1_phi, &b_pfMET_Type1_phi);
  fChain->SetBranchAddress("pfMET_Type1_SumEt", &pfMET_Type1_SumEt, &b_pfMET_Type1_SumEt);
  fChain->SetBranchAddress("pfMET_Type1_PhiCor_pt", &pfMET_Type1_PhiCor_pt, &b_pfMET_Type1_PhiCor_pt);
  fChain->SetBranchAddress("pfMET_Type1_PhiCor_phi", &pfMET_Type1_PhiCor_phi, &b_pfMET_Type1_PhiCor_phi);
  fChain->SetBranchAddress("pfMET_Type1_PhiCor_SumEt", &pfMET_Type1_PhiCor_SumEt, &b_pfMET_Type1_PhiCor_SumEt);
  fChain->SetBranchAddress("pfMET_Type1_pt_shifts", &pfMET_Type1_pt_shifts, &b_pfMET_Type1_pt_shifts);
  fChain->SetBranchAddress("pfMET_Type1_phi_shifts", &pfMET_Type1_phi_shifts, &b_pfMET_Type1_phi_shifts);
  fChain->SetBranchAddress("pfMET_Type1_SumEt_shifts", &pfMET_Type1_SumEt_shifts, &b_pfMET_Type1_SumEt_shifts);
  fChain->SetBranchAddress("pfMET_Type1_PhiCor_pt_shifts", &pfMET_Type1_PhiCor_pt_shifts, &b_pfMET_Type1_PhiCor_pt_shifts);
  fChain->SetBranchAddress("pfMET_Type1_PhiCor_phi_shifts", &pfMET_Type1_PhiCor_phi_shifts, &b_pfMET_Type1_PhiCor_phi_shifts);
  fChain->SetBranchAddress("pfMET_Type1_PhiCor_SumEt_shifts", &pfMET_Type1_PhiCor_SumEt_shifts, &b_pfMET_Type1_PhiCor_SumEt_shifts);
  fChain->SetBranchAddress("PuppiMET_pt", &PuppiMET_pt, &b_PuppiMET_pt);
  fChain->SetBranchAddress("PuppiMET_phi", &PuppiMET_phi, &b_PuppiMET_phi);
  fChain->SetBranchAddress("PuppiMET_SumEt", &PuppiMET_SumEt, &b_PuppiMET_SumEt);
  fChain->SetBranchAddress("PuppiMET_Type1_pt", &PuppiMET_Type1_pt, &b_PuppiMET_Type1_pt);
  fChain->SetBranchAddress("PuppiMET_Type1_phi", &PuppiMET_Type1_phi, &b_PuppiMET_Type1_phi);
  fChain->SetBranchAddress("PuppiMET_Type1_SumEt", &PuppiMET_Type1_SumEt, &b_PuppiMET_Type1_SumEt);
  fChain->SetBranchAddress("PuppiMET_Type1_PhiCor_pt", &PuppiMET_Type1_PhiCor_pt, &b_PuppiMET_Type1_PhiCor_pt);
  fChain->SetBranchAddress("PuppiMET_Type1_PhiCor_phi", &PuppiMET_Type1_PhiCor_phi, &b_PuppiMET_Type1_PhiCor_phi);
  fChain->SetBranchAddress("PuppiMET_Type1_PhiCor_SumEt", &PuppiMET_Type1_PhiCor_SumEt, &b_PuppiMET_Type1_PhiCor_SumEt);
  fChain->SetBranchAddress("PuppiMET_Type1_pt_shifts", &PuppiMET_Type1_pt_shifts, &b_PuppiMET_Type1_pt_shifts);
  fChain->SetBranchAddress("PuppiMET_Type1_phi_shifts", &PuppiMET_Type1_phi_shifts, &b_PuppiMET_Type1_phi_shifts);
  fChain->SetBranchAddress("PuppiMET_Type1_SumEt_shifts", &PuppiMET_Type1_SumEt_shifts, &b_PuppiMET_Type1_SumEt_shifts);
  fChain->SetBranchAddress("tau_phi", &tau_phi, &b_tau_phi);
  fChain->SetBranchAddress("tau_eta", &tau_eta, &b_tau_eta);
  fChain->SetBranchAddress("tau_pt", &tau_pt, &b_tau_pt);
  fChain->SetBranchAddress("tau_mass", &tau_mass, &b_tau_mass);
  fChain->SetBranchAddress("tau_dz", &tau_dz, &b_tau_dz);
  fChain->SetBranchAddress("tau_dxy", &tau_dxy, &b_tau_dxy);
  fChain->SetBranchAddress("tau_decaymode", &tau_decaymode, &b_tau_decaymode);
  fChain->SetBranchAddress("tau_charge", &tau_charge, &b_tau_charge);
  fChain->SetBranchAddress("tau_IDBit", &tau_IDBit, &b_tau_IDBit);
  fChain->SetBranchAddress("tau_idDecayModeNewDMs", &tau_idDecayModeNewDMs, &b_tau_idDecayModeNewDMs);

}












