#define SKFlatNtuple_cxx
#include "SKFlatNtuple.h"
#include <TH2.h>
#include <TStyle.h>
#include <TCanvas.h>

void SKFlatNtuple::Loop(){

  Long64_t nentries = fChain->GetEntries();
  //nentries = 1000;
  //cout << "nentries = " << nentries << endl;

  if(MaxEvent>0){
    nentries = std::min(nentries,MaxEvent);
  }

  cout << "[SKFlatNtuple::Loop] Event Loop Started " << printcurrunttime() << endl;

  for(Long64_t jentry=0; jentry<nentries;jentry++){

    if(jentry<NSkipEvent){
      //cout << "[SKFlatNtuple::Loop] Skipping " << jentry << "'th event" << endl;
      //exit(EXIT_FAILURE);
      continue;
    }

    if(jentry%LogEvery==0){
      cout << "[SKFlatNtuple::Loop] " << jentry << "/" << nentries << " ("<<100.*jentry/nentries<<" %) @ " << printcurrunttime() << endl;
    }

    fChain->GetEntry(jentry);

    executeEvent();

    //std::cout << jentry << " :" << muon_pt->size() << std::endl;

  }

  cout << "[SKFlatNtuple::Loop] JOB FINISHED " << printcurrunttime() << endl;

}

//==== Basic

SKFlatNtuple::SKFlatNtuple(){
  MaxEvent = -1;
  NSkipEvent = 0;
  LogEvery = 1000;
  IsDATA = false;
  DataStream = "";
  MCSample = "";
  weight_norm_1invfb = 1.;
  Userflags.clear();
}

SKFlatNtuple::~SKFlatNtuple()
{
  if (!fChain) return;
  delete fChain->GetCurrentFile();
}

Int_t SKFlatNtuple::GetEntry(Long64_t entry)
{
// Read contents of entry.
  if (!fChain) return 0;
  return fChain->GetEntry(entry);
}

void SKFlatNtuple::Init()
{

  //std::cout << "[SKFlatNtuple::Init] called" << std::endl; 

  if(!IsDATA){

    //std::cout << "[SKFlatNtuple::Init] MCSample = " << MCSample << std::endl;

    TString datadir = getenv("DATA_DIR");
    TString lumitxtpath = datadir+"/Sample/SamplePath.txt";
    //std::cout << "[SKFlatNtuple::Init] lumitxtpath = " << lumitxtpath << endl;

    std::string elline;
    std::ifstream in(lumitxtpath);
    while(getline(in,elline)){
      std::istringstream is( elline );
      TString line = elline;
      TString sample;
      is >> sample;
      //cout << "[SKFlatNtuple::Init] sample = " << sample << std::endl;
      if(sample==MCSample){
        //std::cout << "[SKFlatNtuple::Init] sample==MCSample" << std::endl;
        TString samplefilepath;
        double xsec;
        int N_MC, sumW;
        is >> samplefilepath;
        is >> xsec;
        is >> N_MC;
        is >> sumW;

        //cout << "xsec = " << xsec << endl;
        //cout << "N_MC = " << N_MC << endl;
        //cout << "sumW = " << sumW << endl;

        weight_norm_1invfb = xsec/sumW;

      }
    }
  }

  // Set object pointer
   HLT_TriggerName = 0;
   HLT_TriggerFired = 0;
   HLT_TriggerPrescale = 0;
   jet_pt = 0;
   jet_eta = 0;
   jet_phi = 0;
   jet_charge = 0;
   jet_area = 0;
   jet_partonFlavour = 0;
   jet_hadronFlavour = 0;
   jet_CSVv2 = 0;
   jet_DeepCSV = 0;
   jet_CvsL = 0;
   jet_CvsB = 0;
   jet_DeepFlavour_b = 0;
   jet_DeepFlavour_bb = 0;
   jet_DeepFlavour_lepb = 0;
   jet_DeepFlavour_c = 0;
   jet_DeepFlavour_uds = 0;
   jet_DeepFlavour_g = 0;
   jet_DeepCvsL = 0;
   jet_DeepCvsB = 0;
   jet_chargedHadronEnergyFraction = 0;
   jet_neutralHadronEnergyFraction = 0;
   jet_neutralEmEnergyFraction = 0;
   jet_chargedEmEnergyFraction = 0;
   jet_chargedMultiplicity = 0;
   jet_neutralMultiplicity = 0;
   jet_looseJetID = 0;
   jet_tightJetID = 0;
   jet_tightLepVetoJetID = 0;
   jet_partonPdgId = 0;
   jet_vtxNtracks = 0;
   jet_m = 0;
   jet_energy = 0;
   jet_PileupJetId = 0;
   jet_shiftedEnUp = 0;
   jet_shiftedEnDown = 0;
   fatjet_pt = 0;
   fatjet_eta = 0;
   fatjet_phi = 0;
   fatjet_charge = 0;
   fatjet_area = 0;
   fatjet_partonFlavour = 0;
   fatjet_hadronFlavour = 0;
   fatjet_CSVv2 = 0;
   fatjet_DeepCSV = 0;
   fatjet_DeepFlavour_b = 0;
   fatjet_DeepFlavour_bb = 0;
   fatjet_DeepFlavour_lepb = 0;
   fatjet_DeepFlavour_c = 0;
   fatjet_DeepFlavour_uds = 0;
   fatjet_DeepFlavour_g = 0;
   fatjet_CvsL = 0;
   fatjet_CvsB = 0;
   fatjet_DeepCvsL = 0;
   fatjet_DeepCvsB = 0;
   fatjet_looseJetID = 0;
   fatjet_tightJetID = 0;
   fatjet_tightLepVetoJetID = 0;
   fatjet_partonPdgId = 0;
   fatjet_vtxNtracks = 0;
   fatjet_m = 0;
   fatjet_energy = 0;
   fatjet_puppi_tau1 = 0;
   fatjet_puppi_tau2 = 0;
   fatjet_puppi_tau3 = 0;
   fatjet_puppi_tau4 = 0;
   fatjet_softdropmass = 0;
   fatjet_chargedHadronEnergyFraction = 0;
   fatjet_neutralHadronEnergyFraction = 0;
   fatjet_neutralEmEnergyFraction = 0;
   fatjet_chargedEmEnergyFraction = 0;
   fatjet_chargedMultiplicity = 0;
   fatjet_neutralMultiplicity = 0;
   fatjet_shiftedEnUp = 0;
   fatjet_shiftedEnDown = 0;
   electron_MVAIso = 0;
   electron_MVANoIso = 0;
   electron_et = 0;
   electron_caloEnergy = 0;
   electron_Energy = 0;
   electron_Energy_Scale_Up = 0;
   electron_Energy_Scale_Down = 0;
   electron_Energy_Smear_Up = 0;
   electron_Energy_Smear_Down = 0;
   electron_pt = 0;
   electron_pt_Scale_Up = 0;
   electron_pt_Scale_Down = 0;
   electron_pt_Smear_Up = 0;
   electron_pt_Smear_Down = 0;
   electron_Px = 0;
   electron_Py = 0;
   electron_Pz = 0;
   electron_eta = 0;
   electron_phi = 0;
   electron_charge = 0;
   electron_gsfpt = 0;
   electron_gsfPx = 0;
   electron_gsfPy = 0;
   electron_gsfPz = 0;
   electron_gsfEta = 0;
   electron_gsfPhi = 0;
   electron_gsfCharge = 0;
   electron_scEta = 0;
   electron_scPhi = 0;
   electron_etaWidth = 0;
   electron_phiWidth = 0;
   electron_dEtaIn = 0;
   electron_dEtaInSeed = 0;
   electron_dPhiIn = 0;
   electron_sigmaIEtaIEta = 0;
   electron_Full5x5_SigmaIEtaIEta = 0;
   electron_HoverE = 0;
   electron_fbrem = 0;
   electron_eOverP = 0;
   electron_energyEC = 0;
   electron_Pnorm = 0;
   electron_InvEminusInvP = 0;
   electron_dxyVTX = 0;
   electron_dxyerrVTX = 0;
   electron_dzVTX = 0;
   electron_dzerrVTX = 0;
   electron_3DIPVTX = 0;
   electron_3DIPerrVTX = 0;
   electron_dxy = 0;
   electron_sigdxy = 0;
   electron_dz = 0;
   electron_dxyBS = 0;
   electron_dzBS = 0;
   electron_AEff03 = 0;
   electron_chIso03 = 0;
   electron_nhIso03 = 0;
   electron_phIso03 = 0;
   electron_pcIso03 = 0;
   electron_puChIso03 = 0;
   electron_chIso04 = 0;
   electron_nhIso04 = 0;
   electron_phIso04 = 0;
   electron_pcIso04 = 0;
   electron_puChIso04 = 0;
   electron_relIsoCom03 = 0;
   electron_relIsoCom04 = 0;
   electron_relIsoBeta03 = 0;
   electron_relIsoBeta04 = 0;
   electron_relIsoRho03 = 0;
   electron_passConversionVeto = 0;
   electron_isGsfCtfScPixChargeConsistent = 0;
   electron_mHits = 0;
   electron_crack = 0;
   electron_ecalDriven = 0;
   electron_isoEMHADDepth1 = 0;
   electron_25over55 = 0;
   electron_15over55 = 0;
   electron_isoHADDepth2 = 0;
   electron_isoptTrks = 0;
   electron_modIsoEMHADDepth1 = 0;
   electron_modIsoptTrks = 0;
   electron_modIsoEMHADDepth1Orig = 0;
   electron_modIsoptTrksOrig = 0;
   electron_ambGsf0pt = 0;
   electron_ambGsf0Eta = 0;
   electron_ambGsf0Phi = 0;
   electron_ambGsf0Charge = 0;
   electron_ambGsf1pt = 0;
   electron_ambGsf1Eta = 0;
   electron_ambGsf1Phi = 0;
   electron_ambGsf1Charge = 0;
   electron_ambGsf2pt = 0;
   electron_ambGsf2Eta = 0;
   electron_ambGsf2Phi = 0;
   electron_ambGsf2Charge = 0;
   electron_ambGsf3pt = 0;
   electron_ambGsf3Eta = 0;
   electron_ambGsf3Phi = 0;
   electron_ambGsf3Charge = 0;
   electron_r9 = 0;
   electron_scEnergy = 0;
   electron_scPreEnergy = 0;
   electron_scRawEnergy = 0;
   electron_scEt = 0;
   electron_E15 = 0;
   electron_E25 = 0;
   electron_E55 = 0;
   electron_RelPFIso_dBeta = 0;
   electron_RelPFIso_Rho = 0;
   electron_passVetoID = 0;
   electron_passLooseID = 0;
   electron_passMediumID = 0;
   electron_passTightID = 0;
   electron_passMVAID_noIso_WP80 = 0;
   electron_passMVAID_noIso_WP90 = 0;
   electron_passMVAID_iso_WP80 = 0;
   electron_passMVAID_iso_WP90 = 0;
   electron_passHEEPID = 0;
   electron_EnergyUnCorr = 0;
   electron_mva = 0;
   electron_zzmva = 0;
   electron_chMiniIso = 0;
   electron_nhMiniIso = 0;
   electron_phMiniIso = 0;
   electron_puChMiniIso = 0;
   muon_PfChargedHadronIsoR05 = 0;
   muon_PfNeutralHadronIsoR05 = 0;
   muon_PfGammaIsoR05 = 0;
   muon_PfChargedHadronIsoR04 = 0;
   muon_PfNeutralHadronIsoR04 = 0;
   muon_PfGammaIsoR04 = 0;
   muon_PFSumPUIsoR04 = 0;
   muon_PfChargedHadronIsoR03 = 0;
   muon_PfNeutralHadronIsoR03 = 0;
   muon_PfGammaIsoR03 = 0;
   muon_PFSumPUIsoR03 = 0;
   muon_isPF = 0;
   muon_isGlobal = 0;
   muon_isTracker = 0;
   muon_isStandAlone = 0;
   muon_isTight = 0;
   muon_isMedium = 0;
   muon_isLoose = 0;
   muon_isSoft = 0;
   muon_isHighPt = 0;
   muon_dB = 0;
   muon_phi = 0;
   muon_eta = 0;
   muon_pt = 0;
   muon_mass = 0;
   muon_cktpt = 0;
   muon_cktPx = 0;
   muon_cktPy = 0;
   muon_cktPz = 0;
   muon_cktptError = 0;
   muon_Px = 0;
   muon_Py = 0;
   muon_Pz = 0;
   muon_sumtrkpt = 0;
   muon_trkiso = 0;
   muon_hcaliso = 0;
   muon_ecaliso = 0;
   muon_trkisoR05 = 0;
   muon_hcalisoR05 = 0;
   muon_ecalisoR05 = 0;
   muon_charge = 0;
   muon_nChambers = 0;
   muon_matchedstations = 0;
   muon_stationMask = 0;
   muon_nSegments = 0;
   muon_normchi = 0;
   muon_validhits = 0;
   muon_trackerHits = 0;
   muon_pixelHits = 0;
   muon_validmuonhits = 0;
   muon_trackerLayers = 0;
   muon_qoverp = 0;
   muon_theta = 0;
   muon_lambda = 0;
   muon_dxy = 0;
   muon_d0 = 0;
   muon_dsz = 0;
   muon_dz = 0;
   muon_dxyBS = 0;
   muon_dzBS = 0;
   muon_dszBS = 0;
   muon_dxyVTX = 0;
   muon_dxyerrVTX = 0;
   muon_dzVTX = 0;
   muon_dzerrVTX = 0;
   muon_3DIPVTX = 0;
   muon_3DIPerrVTX = 0;
   muon_dszVTX = 0;
   muon_dxycktVTX = 0;
   muon_dzcktVTX = 0;
   muon_dszcktVTX = 0;
   muon_vx = 0;
   muon_vy = 0;
   muon_vz = 0;
   muon_Best_pt = 0;
   muon_Best_ptError = 0;
   muon_Best_Px = 0;
   muon_Best_Py = 0;
   muon_Best_Pz = 0;
   muon_Best_eta = 0;
   muon_Best_phi = 0;
   muon_Inner_pt = 0;
   muon_Inner_ptError = 0;
   muon_Inner_Px = 0;
   muon_Inner_Py = 0;
   muon_Inner_Pz = 0;
   muon_Inner_eta = 0;
   muon_Inner_phi = 0;
   muon_Outer_pt = 0;
   muon_Outer_ptError = 0;
   muon_Outer_Px = 0;
   muon_Outer_Py = 0;
   muon_Outer_Pz = 0;
   muon_Outer_eta = 0;
   muon_Outer_phi = 0;
   muon_GLB_pt = 0;
   muon_GLB_ptError = 0;
   muon_GLB_Px = 0;
   muon_GLB_Py = 0;
   muon_GLB_Pz = 0;
   muon_GLB_eta = 0;
   muon_GLB_phi = 0;
   muon_TuneP_pt = 0;
   muon_TuneP_ptError = 0;
   muon_TuneP_Px = 0;
   muon_TuneP_Py = 0;
   muon_TuneP_Pz = 0;
   muon_TuneP_eta = 0;
   muon_TuneP_phi = 0;
   muon_roch_sf = 0;
   muon_roch_sf_up = 0;
   muon_PfChargedHadronMiniIso = 0;
   muon_PfNeutralHadronMiniIso = 0;
   muon_PfGammaMiniIso = 0;
   muon_PFSumPUMiniIso = 0;
   PDFWeights_Scale = 0;
   PDFWeights_Error = 0;
   PDFWeights_AlphaS = 0;
   gen_phi = 0;
   gen_eta = 0;
   gen_pt = 0;
   gen_Px = 0;
   gen_Py = 0;
   gen_Pz = 0;
   gen_E = 0;
   gen_mother_PID = 0;
   gen_mother_pt = 0;
   gen_mother_index = 0;
   gen_charge = 0;
   gen_status = 0;
   gen_PID = 0;
   gen_isPrompt = 0;
   gen_isPromptFinalState = 0;
   gen_isTauDecayProduct = 0;
   gen_isPromptTauDecayProduct = 0;
   gen_isDirectPromptTauDecayProductFinalState = 0;
   gen_isHardProcess = 0;
   gen_isLastCopy = 0;
   gen_isLastCopyBeforeFSR = 0;
   gen_isPromptDecayed = 0;
   gen_isDecayedLeptonHadron = 0;
   gen_fromHardProcessBeforeFSR = 0;
   gen_fromHardProcessDecayed = 0;
   gen_fromHardProcessFinalState = 0;
   gen_isMostlyLikePythia6Status3 = 0;
   photon_pt = 0;
   photon_eta = 0;
   photon_phi = 0;
   photon_scEta = 0;
   photon_scPhi = 0;
   photon_HoverE = 0;
   photon_hasPixelSeed = 0;
   photon_Full5x5_SigmaIEtaIEta = 0;
   photon_ChIso = 0;
   photon_NhIso = 0;
   photon_PhIso = 0;
   photon_ChIsoWithEA = 0;
   photon_NhIsoWithEA = 0;
   photon_PhIsoWithEA = 0;
   photon_passMVAID_WP80 = 0;
   photon_passMVAID_WP90 = 0;
   photon_passLooseID = 0;
   photon_passMediumID = 0;
   photon_passTightID = 0;
   photon_ptUnCorr = 0;
  // Set branch addresses and branch pointers

  fChain->SetMakeClass(1);

   fChain->SetBranchAddress("IsData", &IsData, &b_IsData);
   fChain->SetBranchAddress("nTotal", &nTotal, &b_nTotal);
   fChain->SetBranchAddress("run", &run, &b_runNum);
   fChain->SetBranchAddress("event", &event, &b_evtNum);
   fChain->SetBranchAddress("lumi", &lumi, &b_lumiBlock);
   fChain->SetBranchAddress("PUweight", &PUweight, &b_PUweight);
   fChain->SetBranchAddress("Rho", &Rho, &b_Rho);
   fChain->SetBranchAddress("nPV", &nPV, &b_nPV);
   fChain->SetBranchAddress("Flag_goodVertices", &Flag_goodVertices, &b_Flag_goodVertices);
   fChain->SetBranchAddress("Flag_globalTightHalo2016Filter", &Flag_globalTightHalo2016Filter, &b_Flag_globalTightHalo2016Filter);
   fChain->SetBranchAddress("Flag_HBHENoiseFilter", &Flag_HBHENoiseFilter, &b_Flag_HBHENoiseFilter);
   fChain->SetBranchAddress("Flag_HBHENoiseIsoFilter", &Flag_HBHENoiseIsoFilter, &b_Flag_HBHENoiseIsoFilter);
   fChain->SetBranchAddress("Flag_EcalDeadCellTriggerPrimitiveFilter", &Flag_EcalDeadCellTriggerPrimitiveFilter, &b_Flag_EcalDeadCellTriggerPrimitiveFilter);
   fChain->SetBranchAddress("Flag_BadPFMuonFilter", &Flag_BadPFMuonFilter, &b_Flag_BadPFMuonFilter);
   fChain->SetBranchAddress("Flag_BadChargedCandidateFilter", &Flag_BadChargedCandidateFilter, &b_Flag_BadChargedCandidateFilter);
   fChain->SetBranchAddress("Flag_eeBadScFilter", &Flag_eeBadScFilter, &b_Flag_eeBadScFilter);
   fChain->SetBranchAddress("Flag_ecalBadCalibFilter", &Flag_ecalBadCalibFilter, &b_Flag_ecalBadCalibFilter);
   fChain->SetBranchAddress("PVtrackSize", &PVtrackSize, &b_PVtrackSize);
   fChain->SetBranchAddress("PVchi2", &PVchi2, &b_PVchi2);
   fChain->SetBranchAddress("PVndof", &PVndof, &b_PVndof);
   fChain->SetBranchAddress("PVnormalizedChi2", &PVnormalizedChi2, &b_PVnormalizedChi2);
   fChain->SetBranchAddress("vertex_X", &vertex_X, &b_PVx);
   fChain->SetBranchAddress("vertex_Y", &vertex_Y, &b_PVy);
   fChain->SetBranchAddress("vertex_Z", &vertex_Z, &b_PVz);
   fChain->SetBranchAddress("HLT_TriggerName", &HLT_TriggerName, &b_HLT_TriggerName);
   fChain->SetBranchAddress("HLT_TriggerFired", &HLT_TriggerFired, &b_HLT_TriggerFired);
   fChain->SetBranchAddress("HLT_TriggerPrescale", &HLT_TriggerPrescale, &b_HLT_TriggerPrescale);
   fChain->SetBranchAddress("jet_pt", &jet_pt, &b_jet_pt);
   fChain->SetBranchAddress("jet_eta", &jet_eta, &b_jet_eta);
   fChain->SetBranchAddress("jet_phi", &jet_phi, &b_jet_phi);
   fChain->SetBranchAddress("jet_charge", &jet_charge, &b_jet_charge);
   fChain->SetBranchAddress("jet_area", &jet_area, &b_jet_area);
   fChain->SetBranchAddress("jet_partonFlavour", &jet_partonFlavour, &b_jet_partonFlavour);
   fChain->SetBranchAddress("jet_hadronFlavour", &jet_hadronFlavour, &b_jet_hadronFlavour);
   fChain->SetBranchAddress("jet_CSVv2", &jet_CSVv2, &b_jet_CSVv2);
   fChain->SetBranchAddress("jet_DeepCSV", &jet_DeepCSV, &b_jet_DeepCSV);
   fChain->SetBranchAddress("jet_CvsL", &jet_CvsL, &b_jet_CvsL);
   fChain->SetBranchAddress("jet_CvsB", &jet_CvsB, &b_jet_CvsB);
   fChain->SetBranchAddress("jet_DeepFlavour_b", &jet_DeepFlavour_b, &b_jet_DeepFlavour_b);
   fChain->SetBranchAddress("jet_DeepFlavour_bb", &jet_DeepFlavour_bb, &b_jet_DeepFlavour_bb);
   fChain->SetBranchAddress("jet_DeepFlavour_lepb", &jet_DeepFlavour_lepb, &b_jet_DeepFlavour_lepb);
   fChain->SetBranchAddress("jet_DeepFlavour_c", &jet_DeepFlavour_c, &b_jet_DeepFlavour_c);
   fChain->SetBranchAddress("jet_DeepFlavour_uds", &jet_DeepFlavour_uds, &b_jet_DeepFlavour_uds);
   fChain->SetBranchAddress("jet_DeepFlavour_g", &jet_DeepFlavour_g, &b_jet_DeepFlavour_g);
   fChain->SetBranchAddress("jet_DeepCvsL", &jet_DeepCvsL, &b_jet_DeepCvsL);
   fChain->SetBranchAddress("jet_DeepCvsB", &jet_DeepCvsB, &b_jet_DeepCvsB);
   fChain->SetBranchAddress("jet_chargedHadronEnergyFraction", &jet_chargedHadronEnergyFraction, &b_jet_chargedHadronEnergyFraction);
   fChain->SetBranchAddress("jet_neutralHadronEnergyFraction", &jet_neutralHadronEnergyFraction, &b_jet_neutralHadronEnergyFraction);
   fChain->SetBranchAddress("jet_neutralEmEnergyFraction", &jet_neutralEmEnergyFraction, &b_jet_neutralEmEnergyFraction);
   fChain->SetBranchAddress("jet_chargedEmEnergyFraction", &jet_chargedEmEnergyFraction, &b_jet_chargedEmEnergyFraction);
   fChain->SetBranchAddress("jet_chargedMultiplicity", &jet_chargedMultiplicity, &b_jet_chargedMultiplicity);
   fChain->SetBranchAddress("jet_neutralMultiplicity", &jet_neutralMultiplicity, &b_jet_neutralMultiplicity);
   fChain->SetBranchAddress("jet_looseJetID", &jet_looseJetID, &b_jet_looseJetID);
   fChain->SetBranchAddress("jet_tightJetID", &jet_tightJetID, &b_jet_tightJetID);
   fChain->SetBranchAddress("jet_tightLepVetoJetID", &jet_tightLepVetoJetID, &b_jet_tightLepVetoJetID);
   fChain->SetBranchAddress("jet_partonPdgId", &jet_partonPdgId, &b_jet_partonPdgId);
   fChain->SetBranchAddress("jet_vtxNtracks", &jet_vtxNtracks, &b_jet_vtxNtracks);
   fChain->SetBranchAddress("jet_m", &jet_m, &b_jet_m);
   fChain->SetBranchAddress("jet_energy", &jet_energy, &b_jet_energy);
   fChain->SetBranchAddress("jet_PileupJetId", &jet_PileupJetId, &b_jet_PileupJetId);
   fChain->SetBranchAddress("jet_shiftedEnUp", &jet_shiftedEnUp, &b_jet_shiftedEnUp);
   fChain->SetBranchAddress("jet_shiftedEnDown", &jet_shiftedEnDown, &b_jet_shiftedEnDown);
   fChain->SetBranchAddress("fatjet_pt", &fatjet_pt, &b_fatjet_pt);
   fChain->SetBranchAddress("fatjet_eta", &fatjet_eta, &b_fatjet_eta);
   fChain->SetBranchAddress("fatjet_phi", &fatjet_phi, &b_fatjet_phi);
   fChain->SetBranchAddress("fatjet_charge", &fatjet_charge, &b_fatjet_charge);
   fChain->SetBranchAddress("fatjet_area", &fatjet_area, &b_fatjet_area);
   fChain->SetBranchAddress("fatjet_partonFlavour", &fatjet_partonFlavour, &b_fatjet_partonFlavour);
   fChain->SetBranchAddress("fatjet_hadronFlavour", &fatjet_hadronFlavour, &b_fatjet_hadronFlavour);
   fChain->SetBranchAddress("fatjet_CSVv2", &fatjet_CSVv2, &b_fatjet_CSVv2);
   fChain->SetBranchAddress("fatjet_DeepCSV", &fatjet_DeepCSV, &b_fatjet_DeepCSV);
   fChain->SetBranchAddress("fatjet_DeepFlavour_b", &fatjet_DeepFlavour_b, &b_fatjet_DeepFlavour_b);
   fChain->SetBranchAddress("fatjet_DeepFlavour_bb", &fatjet_DeepFlavour_bb, &b_fatjet_DeepFlavour_bb);
   fChain->SetBranchAddress("fatjet_DeepFlavour_lepb", &fatjet_DeepFlavour_lepb, &b_fatjet_DeepFlavour_lepb);
   fChain->SetBranchAddress("fatjet_DeepFlavour_c", &fatjet_DeepFlavour_c, &b_fatjet_DeepFlavour_c);
   fChain->SetBranchAddress("fatjet_DeepFlavour_uds", &fatjet_DeepFlavour_uds, &b_fatjet_DeepFlavour_uds);
   fChain->SetBranchAddress("fatjet_DeepFlavour_g", &fatjet_DeepFlavour_g, &b_fatjet_DeepFlavour_g);
   fChain->SetBranchAddress("fatjet_CvsL", &fatjet_CvsL, &b_fatjet_CvsL);
   fChain->SetBranchAddress("fatjet_CvsB", &fatjet_CvsB, &b_fatjet_CvsB);
   fChain->SetBranchAddress("fatjet_DeepCvsL", &fatjet_DeepCvsL, &b_fatjet_DeepCvsL);
   fChain->SetBranchAddress("fatjet_DeepCvsB", &fatjet_DeepCvsB, &b_fatjet_DeepCvsB);
   fChain->SetBranchAddress("fatjet_looseJetID", &fatjet_looseJetID, &b_fatjet_looseJetID);
   fChain->SetBranchAddress("fatjet_tightJetID", &fatjet_tightJetID, &b_fatjet_tightJetID);
   fChain->SetBranchAddress("fatjet_tightLepVetoJetID", &fatjet_tightLepVetoJetID, &b_fatjet_tightLepVetoJetID);
   fChain->SetBranchAddress("fatjet_partonPdgId", &fatjet_partonPdgId, &b_fatjet_partonPdgId);
   fChain->SetBranchAddress("fatjet_vtxNtracks", &fatjet_vtxNtracks, &b_fatjet_vtxNtracks);
   fChain->SetBranchAddress("fatjet_m", &fatjet_m, &b_fatjet_m);
   fChain->SetBranchAddress("fatjet_energy", &fatjet_energy, &b_fatjet_energy);
   fChain->SetBranchAddress("fatjet_puppi_tau1", &fatjet_puppi_tau1, &b_fatjet_puppi_tau1);
   fChain->SetBranchAddress("fatjet_puppi_tau2", &fatjet_puppi_tau2, &b_fatjet_puppi_tau2);
   fChain->SetBranchAddress("fatjet_puppi_tau3", &fatjet_puppi_tau3, &b_fatjet_puppi_tau3);
   fChain->SetBranchAddress("fatjet_puppi_tau4", &fatjet_puppi_tau4, &b_fatjet_puppi_tau4);
   fChain->SetBranchAddress("fatjet_softdropmass", &fatjet_softdropmass, &b_fatjet_softdropmass);
   fChain->SetBranchAddress("fatjet_chargedHadronEnergyFraction", &fatjet_chargedHadronEnergyFraction, &b_fatjet_chargedHadronEnergyFraction);
   fChain->SetBranchAddress("fatjet_neutralHadronEnergyFraction", &fatjet_neutralHadronEnergyFraction, &b_fatjet_neutralHadronEnergyFraction);
   fChain->SetBranchAddress("fatjet_neutralEmEnergyFraction", &fatjet_neutralEmEnergyFraction, &b_fatjet_neutralEmEnergyFraction);
   fChain->SetBranchAddress("fatjet_chargedEmEnergyFraction", &fatjet_chargedEmEnergyFraction, &b_fatjet_chargedEmEnergyFraction);
   fChain->SetBranchAddress("fatjet_chargedMultiplicity", &fatjet_chargedMultiplicity, &b_fatjet_chargedMultiplicity);
   fChain->SetBranchAddress("fatjet_neutralMultiplicity", &fatjet_neutralMultiplicity, &b_fatjet_neutralMultiplicity);
   fChain->SetBranchAddress("fatjet_shiftedEnUp", &fatjet_shiftedEnUp, &b_fatjet_shiftedEnUp);
   fChain->SetBranchAddress("fatjet_shiftedEnDown", &fatjet_shiftedEnDown, &b_fatjet_shiftedEnDown);
   fChain->SetBranchAddress("electron_MVAIso", &electron_MVAIso, &b_electron_MVAIso);
   fChain->SetBranchAddress("electron_MVANoIso", &electron_MVANoIso, &b_electron_MVANoIso);
   fChain->SetBranchAddress("electron_et", &electron_et, &b_electron_et);
   fChain->SetBranchAddress("electron_caloEnergy", &electron_caloEnergy, &b_electron_caloEnergy);
   fChain->SetBranchAddress("electron_Energy", &electron_Energy, &b_electron_Energy);
   fChain->SetBranchAddress("electron_Energy_Scale_Up", &electron_Energy_Scale_Up, &b_electron_Energy_Scale_Up);
   fChain->SetBranchAddress("electron_Energy_Scale_Down", &electron_Energy_Scale_Down, &b_electron_Energy_Scale_Down);
   fChain->SetBranchAddress("electron_Energy_Smear_Up", &electron_Energy_Smear_Up, &b_electron_Energy_Smear_Up);
   fChain->SetBranchAddress("electron_Energy_Smear_Down", &electron_Energy_Smear_Down, &b_electron_Energy_Smear_Down);
   fChain->SetBranchAddress("electron_pt", &electron_pt, &b_electron_pt);
   fChain->SetBranchAddress("electron_pt_Scale_Up", &electron_pt_Scale_Up, &b_electron_pt_Scale_Up);
   fChain->SetBranchAddress("electron_pt_Scale_Down", &electron_pt_Scale_Down, &b_electron_pt_Scale_Down);
   fChain->SetBranchAddress("electron_pt_Smear_Up", &electron_pt_Smear_Up, &b_electron_pt_Smear_Up);
   fChain->SetBranchAddress("electron_pt_Smear_Down", &electron_pt_Smear_Down, &b_electron_pt_Smear_Down);
   fChain->SetBranchAddress("electron_Px", &electron_Px, &b_electron_Px);
   fChain->SetBranchAddress("electron_Py", &electron_Py, &b_electron_Py);
   fChain->SetBranchAddress("electron_Pz", &electron_Pz, &b_electron_Pz);
   fChain->SetBranchAddress("electron_eta", &electron_eta, &b_electron_eta);
   fChain->SetBranchAddress("electron_phi", &electron_phi, &b_electron_phi);
   fChain->SetBranchAddress("electron_charge", &electron_charge, &b_electron_charge);
   fChain->SetBranchAddress("electron_gsfpt", &electron_gsfpt, &b_electron_gsfpt);
   fChain->SetBranchAddress("electron_gsfPx", &electron_gsfPx, &b_electron_gsfPx);
   fChain->SetBranchAddress("electron_gsfPy", &electron_gsfPy, &b_electron_gsfPy);
   fChain->SetBranchAddress("electron_gsfPz", &electron_gsfPz, &b_electron_gsfPz);
   fChain->SetBranchAddress("electron_gsfEta", &electron_gsfEta, &b_electron_gsfEta);
   fChain->SetBranchAddress("electron_gsfPhi", &electron_gsfPhi, &b_electron_gsfPhi);
   fChain->SetBranchAddress("electron_gsfCharge", &electron_gsfCharge, &b_electron_gsfCharge);
   fChain->SetBranchAddress("electron_scEta", &electron_scEta, &b_electron_scEta);
   fChain->SetBranchAddress("electron_scPhi", &electron_scPhi, &b_electron_scPhi);
   fChain->SetBranchAddress("electron_etaWidth", &electron_etaWidth, &b_electron_etaWidth);
   fChain->SetBranchAddress("electron_phiWidth", &electron_phiWidth, &b_electron_phiWidth);
   fChain->SetBranchAddress("electron_dEtaIn", &electron_dEtaIn, &b_electron_dEtaIn);
   fChain->SetBranchAddress("electron_dEtaInSeed", &electron_dEtaInSeed, &b_electron_dEtaInSeed);
   fChain->SetBranchAddress("electron_dPhiIn", &electron_dPhiIn, &b_electron_dPhiIn);
   fChain->SetBranchAddress("electron_sigmaIEtaIEta", &electron_sigmaIEtaIEta, &b_electron_sigmaIEtaIEta);
   fChain->SetBranchAddress("electron_Full5x5_SigmaIEtaIEta", &electron_Full5x5_SigmaIEtaIEta, &b_electron_Full5x5_SigmaIEtaIEta);
   fChain->SetBranchAddress("electron_HoverE", &electron_HoverE, &b_electron_HoverE);
   fChain->SetBranchAddress("electron_fbrem", &electron_fbrem, &b_electron_fbrem);
   fChain->SetBranchAddress("electron_eOverP", &electron_eOverP, &b_electron_eOverP);
   fChain->SetBranchAddress("electron_energyEC", &electron_energyEC, &b_electron_energyEC);
   fChain->SetBranchAddress("electron_Pnorm", &electron_Pnorm, &b_electron_Pnorm);
   fChain->SetBranchAddress("electron_InvEminusInvP", &electron_InvEminusInvP, &b_electron_InvEminusInvP);
   fChain->SetBranchAddress("electron_dxyVTX", &electron_dxyVTX, &b_electron_dxyVTX);
   fChain->SetBranchAddress("electron_dxyerrVTX", &electron_dxyerrVTX, &b_electron_dxyerrVTX);
   fChain->SetBranchAddress("electron_dzVTX", &electron_dzVTX, &b_electron_dzVTX);
   fChain->SetBranchAddress("electron_dzerrVTX", &electron_dzerrVTX, &b_electron_dzerrVTX);
   fChain->SetBranchAddress("electron_3DIPVTX", &electron_3DIPVTX, &b_electron_3DIPVTX);
   fChain->SetBranchAddress("electron_3DIPerrVTX", &electron_3DIPerrVTX, &b_electron_3DIPerrVTX);
   fChain->SetBranchAddress("electron_dxy", &electron_dxy, &b_electron_dxy);
   fChain->SetBranchAddress("electron_sigdxy", &electron_sigdxy, &b_electron_sigdxy);
   fChain->SetBranchAddress("electron_dz", &electron_dz, &b_electron_dz);
   fChain->SetBranchAddress("electron_dxyBS", &electron_dxyBS, &b_electron_dxyBS);
   fChain->SetBranchAddress("electron_dzBS", &electron_dzBS, &b_electron_dzBS);
   fChain->SetBranchAddress("electron_AEff03", &electron_AEff03, &b_electron_AEff03);
   fChain->SetBranchAddress("electron_chIso03", &electron_chIso03, &b_electron_chIso03);
   fChain->SetBranchAddress("electron_nhIso03", &electron_nhIso03, &b_electron_nhIso03);
   fChain->SetBranchAddress("electron_phIso03", &electron_phIso03, &b_electron_phIso03);
   fChain->SetBranchAddress("electron_pcIso03", &electron_pcIso03, &b_electron_pcIso03);
   fChain->SetBranchAddress("electron_puChIso03", &electron_puChIso03, &b_electron_puChIso03);
   fChain->SetBranchAddress("electron_chIso04", &electron_chIso04, &b_electron_chIso04);
   fChain->SetBranchAddress("electron_nhIso04", &electron_nhIso04, &b_electron_nhIso04);
   fChain->SetBranchAddress("electron_phIso04", &electron_phIso04, &b_electron_phIso04);
   fChain->SetBranchAddress("electron_pcIso04", &electron_pcIso04, &b_electron_pcIso04);
   fChain->SetBranchAddress("electron_puChIso04", &electron_puChIso04, &b_electron_puChIso04);
   fChain->SetBranchAddress("electron_relIsoCom03", &electron_relIsoCom03, &b_electron_relIsoCom03);
   fChain->SetBranchAddress("electron_relIsoCom04", &electron_relIsoCom04, &b_electron_relIsoCom04);
   fChain->SetBranchAddress("electron_relIsoBeta03", &electron_relIsoBeta03, &b_electron_relIsoBeta03);
   fChain->SetBranchAddress("electron_relIsoBeta04", &electron_relIsoBeta04, &b_electron_relIsoBeta04);
   fChain->SetBranchAddress("electron_relIsoRho03", &electron_relIsoRho03, &b_electron_relIsoRho03);
   fChain->SetBranchAddress("electron_passConversionVeto", &electron_passConversionVeto, &b_electron_passConversionVeto);
   fChain->SetBranchAddress("electron_isGsfCtfScPixChargeConsistent", &electron_isGsfCtfScPixChargeConsistent, &b_electron_isGsfCtfScPixChargeConsistent);
   fChain->SetBranchAddress("electron_mHits", &electron_mHits, &b_electron_mHits);
   fChain->SetBranchAddress("electron_crack", &electron_crack, &b_electron_crack);
   fChain->SetBranchAddress("electron_ecalDriven", &electron_ecalDriven, &b_electron_ecalDriven);
   fChain->SetBranchAddress("electron_isoEMHADDepth1", &electron_isoEMHADDepth1, &b_electron_isoEMHADDepth1);
   fChain->SetBranchAddress("electron_25over55", &electron_25over55, &b_electron_25over55);
   fChain->SetBranchAddress("electron_15over55", &electron_15over55, &b_electron_15over55);
   fChain->SetBranchAddress("electron_isoHADDepth2", &electron_isoHADDepth2, &b_electron_isoHADDepth2);
   fChain->SetBranchAddress("electron_isoptTrks", &electron_isoptTrks, &b_electron_isoptTrks);
   fChain->SetBranchAddress("electron_modIsoEMHADDepth1", &electron_modIsoEMHADDepth1, &b_electron_modIsoEMHADDepth1);
   fChain->SetBranchAddress("electron_modIsoptTrks", &electron_modIsoptTrks, &b_electron_modIsoptTrks);
   fChain->SetBranchAddress("electron_modIsoEMHADDepth1Orig", &electron_modIsoEMHADDepth1Orig, &b_electron_modIsoEMHADDepth1Orig);
   fChain->SetBranchAddress("electron_modIsoptTrksOrig", &electron_modIsoptTrksOrig, &b_electron_modIsoptTrksOrig);
   fChain->SetBranchAddress("electron_ambGsf0pt", &electron_ambGsf0pt, &b_electron_ambGsf0pt);
   fChain->SetBranchAddress("electron_ambGsf0Eta", &electron_ambGsf0Eta, &b_electron_ambGsf0Eta);
   fChain->SetBranchAddress("electron_ambGsf0Phi", &electron_ambGsf0Phi, &b_electron_ambGsf0Phi);
   fChain->SetBranchAddress("electron_ambGsf0Charge", &electron_ambGsf0Charge, &b_electron_ambGsf0Charge);
   fChain->SetBranchAddress("electron_ambGsf1pt", &electron_ambGsf1pt, &b_electron_ambGsf1pt);
   fChain->SetBranchAddress("electron_ambGsf1Eta", &electron_ambGsf1Eta, &b_electron_ambGsf1Eta);
   fChain->SetBranchAddress("electron_ambGsf1Phi", &electron_ambGsf1Phi, &b_electron_ambGsf1Phi);
   fChain->SetBranchAddress("electron_ambGsf1Charge", &electron_ambGsf1Charge, &b_electron_ambGsf1Charge);
   fChain->SetBranchAddress("electron_ambGsf2pt", &electron_ambGsf2pt, &b_electron_ambGsf2pt);
   fChain->SetBranchAddress("electron_ambGsf2Eta", &electron_ambGsf2Eta, &b_electron_ambGsf2Eta);
   fChain->SetBranchAddress("electron_ambGsf2Phi", &electron_ambGsf2Phi, &b_electron_ambGsf2Phi);
   fChain->SetBranchAddress("electron_ambGsf2Charge", &electron_ambGsf2Charge, &b_electron_ambGsf2Charge);
   fChain->SetBranchAddress("electron_ambGsf3pt", &electron_ambGsf3pt, &b_electron_ambGsf3pt);
   fChain->SetBranchAddress("electron_ambGsf3Eta", &electron_ambGsf3Eta, &b_electron_ambGsf3Eta);
   fChain->SetBranchAddress("electron_ambGsf3Phi", &electron_ambGsf3Phi, &b_electron_ambGsf3Phi);
   fChain->SetBranchAddress("electron_ambGsf3Charge", &electron_ambGsf3Charge, &b_electron_ambGsf3Charge);
   fChain->SetBranchAddress("electron_r9", &electron_r9, &b_electron_r9);
   fChain->SetBranchAddress("electron_scEnergy", &electron_scEnergy, &b_electron_scEnergy);
   fChain->SetBranchAddress("electron_scPreEnergy", &electron_scPreEnergy, &b_electron_scPreEnergy);
   fChain->SetBranchAddress("electron_scRawEnergy", &electron_scRawEnergy, &b_electron_scRawEnergy);
   fChain->SetBranchAddress("electron_scEt", &electron_scEt, &b_electron_scEt);
   fChain->SetBranchAddress("electron_E15", &electron_E15, &b_electron_E15);
   fChain->SetBranchAddress("electron_E25", &electron_E25, &b_electron_E25);
   fChain->SetBranchAddress("electron_E55", &electron_E55, &b_electron_E55);
   fChain->SetBranchAddress("electron_RelPFIso_dBeta", &electron_RelPFIso_dBeta, &b_electron_RelPFIso_dBeta);
   fChain->SetBranchAddress("electron_RelPFIso_Rho", &electron_RelPFIso_Rho, &b_electron_RelPFIso_Rho);
   fChain->SetBranchAddress("electron_passVetoID", &electron_passVetoID, &b_electron_passVetoID);
   fChain->SetBranchAddress("electron_passLooseID", &electron_passLooseID, &b_electron_passLooseID);
   fChain->SetBranchAddress("electron_passMediumID", &electron_passMediumID, &b_electron_passMediumID);
   fChain->SetBranchAddress("electron_passTightID", &electron_passTightID, &b_electron_passTightID);
   fChain->SetBranchAddress("electron_passMVAID_noIso_WP80", &electron_passMVAID_noIso_WP80, &b_electron_passMVAID_noIso_WP80);
   fChain->SetBranchAddress("electron_passMVAID_noIso_WP90", &electron_passMVAID_noIso_WP90, &b_electron_passMVAID_noIso_WP90);
   fChain->SetBranchAddress("electron_passMVAID_iso_WP80", &electron_passMVAID_iso_WP80, &b_electron_passMVAID_iso_WP80);
   fChain->SetBranchAddress("electron_passMVAID_iso_WP90", &electron_passMVAID_iso_WP90, &b_electron_passMVAID_iso_WP90);
   fChain->SetBranchAddress("electron_passHEEPID", &electron_passHEEPID, &b_electron_passHEEPID);
   fChain->SetBranchAddress("electron_EnergyUnCorr", &electron_EnergyUnCorr, &b_electron_EnergyUnCorr);
   fChain->SetBranchAddress("electron_mva", &electron_mva, &b_electron_mva);
   fChain->SetBranchAddress("electron_zzmva", &electron_zzmva, &b_electron_zzmva);
   fChain->SetBranchAddress("electron_chMiniIso", &electron_chMiniIso, &b_electron_chMiniIso);
   fChain->SetBranchAddress("electron_nhMiniIso", &electron_nhMiniIso, &b_electron_nhMiniIso);
   fChain->SetBranchAddress("electron_phMiniIso", &electron_phMiniIso, &b_electron_phMiniIso);
   fChain->SetBranchAddress("electron_puChMiniIso", &electron_puChMiniIso, &b_electron_puChMiniIso);
   fChain->SetBranchAddress("muon_PfChargedHadronIsoR05", &muon_PfChargedHadronIsoR05, &b_muon_PfChargedHadronIsoR05);
   fChain->SetBranchAddress("muon_PfNeutralHadronIsoR05", &muon_PfNeutralHadronIsoR05, &b_muon_PfNeutralHadronIsoR05);
   fChain->SetBranchAddress("muon_PfGammaIsoR05", &muon_PfGammaIsoR05, &b_muon_PfGammaIsoR05);
   fChain->SetBranchAddress("muon_PfChargedHadronIsoR04", &muon_PfChargedHadronIsoR04, &b_muon_PfChargedHadronIsoR04);
   fChain->SetBranchAddress("muon_PfNeutralHadronIsoR04", &muon_PfNeutralHadronIsoR04, &b_muon_PfNeutralHadronIsoR04);
   fChain->SetBranchAddress("muon_PfGammaIsoR04", &muon_PfGammaIsoR04, &b_muon_PfGammaIsoR04);
   fChain->SetBranchAddress("muon_PFSumPUIsoR04", &muon_PFSumPUIsoR04, &b_muon_PFSumPUIsoR04);
   fChain->SetBranchAddress("muon_PfChargedHadronIsoR03", &muon_PfChargedHadronIsoR03, &b_muon_PfChargedHadronIsoR03);
   fChain->SetBranchAddress("muon_PfNeutralHadronIsoR03", &muon_PfNeutralHadronIsoR03, &b_muon_PfNeutralHadronIsoR03);
   fChain->SetBranchAddress("muon_PfGammaIsoR03", &muon_PfGammaIsoR03, &b_muon_PfGammaIsoR03);
   fChain->SetBranchAddress("muon_PFSumPUIsoR03", &muon_PFSumPUIsoR03, &b_muon_PFSumPUIsoR03);
   fChain->SetBranchAddress("muon_isPF", &muon_isPF, &b_muon_isPF);
   fChain->SetBranchAddress("muon_isGlobal", &muon_isGlobal, &b_muon_isGlobal);
   fChain->SetBranchAddress("muon_isTracker", &muon_isTracker, &b_muon_isTracker);
   fChain->SetBranchAddress("muon_isStandAlone", &muon_isStandAlone, &b_muon_isStandAlone);
   fChain->SetBranchAddress("muon_isTight", &muon_isTight, &b_muon_isTight);
   fChain->SetBranchAddress("muon_isMedium", &muon_isMedium, &b_muon_isMedium);
   fChain->SetBranchAddress("muon_isLoose", &muon_isLoose, &b_muon_isLoose);
   fChain->SetBranchAddress("muon_isSoft", &muon_isSoft, &b_muon_isSoft);
   fChain->SetBranchAddress("muon_isHighPt", &muon_isHighPt, &b_muon_isHighPt);
   fChain->SetBranchAddress("muon_dB", &muon_dB, &b_muon_dB);
   fChain->SetBranchAddress("muon_phi", &muon_phi, &b_muon_phi);
   fChain->SetBranchAddress("muon_eta", &muon_eta, &b_muon_eta);
   fChain->SetBranchAddress("muon_pt", &muon_pt, &b_muon_pt);
   fChain->SetBranchAddress("muon_mass", &muon_mass, &b_muon_mass);
   fChain->SetBranchAddress("muon_cktpt", &muon_cktpt, &b_muon_cktpt);
   fChain->SetBranchAddress("muon_cktPx", &muon_cktPx, &b_muon_cktPx);
   fChain->SetBranchAddress("muon_cktPy", &muon_cktPy, &b_muon_cktPy);
   fChain->SetBranchAddress("muon_cktPz", &muon_cktPz, &b_muon_cktPz);
   fChain->SetBranchAddress("muon_cktptError", &muon_cktptError, &b_muon_cktptError);
   fChain->SetBranchAddress("muon_Px", &muon_Px, &b_muon_Px);
   fChain->SetBranchAddress("muon_Py", &muon_Py, &b_muon_Py);
   fChain->SetBranchAddress("muon_Pz", &muon_Pz, &b_muon_Pz);
   fChain->SetBranchAddress("muon_sumtrkpt", &muon_sumtrkpt, &b_muon_sumtrkpt);
   fChain->SetBranchAddress("muon_trkiso", &muon_trkiso, &b_muon_trkiso);
   fChain->SetBranchAddress("muon_hcaliso", &muon_hcaliso, &b_muon_hcaliso);
   fChain->SetBranchAddress("muon_ecaliso", &muon_ecaliso, &b_muon_ecaliso);
   fChain->SetBranchAddress("muon_trkisoR05", &muon_trkisoR05, &b_muon_trkisoR05);
   fChain->SetBranchAddress("muon_hcalisoR05", &muon_hcalisoR05, &b_muon_hcalisoR05);
   fChain->SetBranchAddress("muon_ecalisoR05", &muon_ecalisoR05, &b_muon_ecalisoR05);
   fChain->SetBranchAddress("muon_charge", &muon_charge, &b_muon_charge);
   fChain->SetBranchAddress("muon_nChambers", &muon_nChambers, &b_muon_nChambers);
   fChain->SetBranchAddress("muon_matchedstations", &muon_matchedstations, &b_muon_matchedstations);
   fChain->SetBranchAddress("muon_stationMask", &muon_stationMask, &b_muon_stationMask);
   fChain->SetBranchAddress("muon_nSegments", &muon_nSegments, &b_muon_nSegments);
   fChain->SetBranchAddress("muon_normchi", &muon_normchi, &b_muon_normchi);
   fChain->SetBranchAddress("muon_validhits", &muon_validhits, &b_muon_validhits);
   fChain->SetBranchAddress("muon_trackerHits", &muon_trackerHits, &b_muon_trackerHits);
   fChain->SetBranchAddress("muon_pixelHits", &muon_pixelHits, &b_muon_pixelHits);
   fChain->SetBranchAddress("muon_validmuonhits", &muon_validmuonhits, &b_muon_validmuonhits);
   fChain->SetBranchAddress("muon_trackerLayers", &muon_trackerLayers, &b_muon_trackerLayers);
   fChain->SetBranchAddress("muon_qoverp", &muon_qoverp, &b_muon_qoverp);
   fChain->SetBranchAddress("muon_theta", &muon_theta, &b_muon_theta);
   fChain->SetBranchAddress("muon_lambda", &muon_lambda, &b_muon_lambda);
   fChain->SetBranchAddress("muon_dxy", &muon_dxy, &b_muon_dxy);
   fChain->SetBranchAddress("muon_d0", &muon_d0, &b_muon_d0);
   fChain->SetBranchAddress("muon_dsz", &muon_dsz, &b_muon_dsz);
   fChain->SetBranchAddress("muon_dz", &muon_dz, &b_muon_dz);
   fChain->SetBranchAddress("muon_dxyBS", &muon_dxyBS, &b_muon_dxyBS);
   fChain->SetBranchAddress("muon_dzBS", &muon_dzBS, &b_muon_dzBS);
   fChain->SetBranchAddress("muon_dszBS", &muon_dszBS, &b_muon_dszBS);
   fChain->SetBranchAddress("muon_dxyVTX", &muon_dxyVTX, &b_muon_dxyVTX);
   fChain->SetBranchAddress("muon_dxyerrVTX", &muon_dxyerrVTX, &b_muon_dxyerrVTX);
   fChain->SetBranchAddress("muon_dzVTX", &muon_dzVTX, &b_muon_dzVTX);
   fChain->SetBranchAddress("muon_dzerrVTX", &muon_dzerrVTX, &b_muon_dzerrVTX);
   fChain->SetBranchAddress("muon_3DIPVTX", &muon_3DIPVTX, &b_muon_3DIPVTX);
   fChain->SetBranchAddress("muon_3DIPerrVTX", &muon_3DIPerrVTX, &b_muon_3DIPerrVTX);
   fChain->SetBranchAddress("muon_dszVTX", &muon_dszVTX, &b_muon_dszVTX);
   fChain->SetBranchAddress("muon_dxycktVTX", &muon_dxycktVTX, &b_muon_dxycktVTX);
   fChain->SetBranchAddress("muon_dzcktVTX", &muon_dzcktVTX, &b_muon_dzcktVTX);
   fChain->SetBranchAddress("muon_dszcktVTX", &muon_dszcktVTX, &b_muon_dszcktVTX);
   fChain->SetBranchAddress("muon_vx", &muon_vx, &b_muon_vx);
   fChain->SetBranchAddress("muon_vy", &muon_vy, &b_muon_vy);
   fChain->SetBranchAddress("muon_vz", &muon_vz, &b_muon_vz);
   fChain->SetBranchAddress("muon_Best_pt", &muon_Best_pt, &b_muon_Best_pt);
   fChain->SetBranchAddress("muon_Best_ptError", &muon_Best_ptError, &b_muon_Best_ptError);
   fChain->SetBranchAddress("muon_Best_Px", &muon_Best_Px, &b_muon_Best_Px);
   fChain->SetBranchAddress("muon_Best_Py", &muon_Best_Py, &b_muon_Best_Py);
   fChain->SetBranchAddress("muon_Best_Pz", &muon_Best_Pz, &b_muon_Best_Pz);
   fChain->SetBranchAddress("muon_Best_eta", &muon_Best_eta, &b_muon_Best_eta);
   fChain->SetBranchAddress("muon_Best_phi", &muon_Best_phi, &b_muon_Best_phi);
   fChain->SetBranchAddress("muon_Inner_pt", &muon_Inner_pt, &b_muon_Inner_pt);
   fChain->SetBranchAddress("muon_Inner_ptError", &muon_Inner_ptError, &b_muon_Inner_ptError);
   fChain->SetBranchAddress("muon_Inner_Px", &muon_Inner_Px, &b_muon_Inner_Px);
   fChain->SetBranchAddress("muon_Inner_Py", &muon_Inner_Py, &b_muon_Inner_Py);
   fChain->SetBranchAddress("muon_Inner_Pz", &muon_Inner_Pz, &b_muon_Inner_Pz);
   fChain->SetBranchAddress("muon_Inner_eta", &muon_Inner_eta, &b_muon_Inner_eta);
   fChain->SetBranchAddress("muon_Inner_phi", &muon_Inner_phi, &b_muon_Inner_phi);
   fChain->SetBranchAddress("muon_Outer_pt", &muon_Outer_pt, &b_muon_Outer_pt);
   fChain->SetBranchAddress("muon_Outer_ptError", &muon_Outer_ptError, &b_muon_Outer_ptError);
   fChain->SetBranchAddress("muon_Outer_Px", &muon_Outer_Px, &b_muon_Outer_Px);
   fChain->SetBranchAddress("muon_Outer_Py", &muon_Outer_Py, &b_muon_Outer_Py);
   fChain->SetBranchAddress("muon_Outer_Pz", &muon_Outer_Pz, &b_muon_Outer_Pz);
   fChain->SetBranchAddress("muon_Outer_eta", &muon_Outer_eta, &b_muon_Outer_eta);
   fChain->SetBranchAddress("muon_Outer_phi", &muon_Outer_phi, &b_muon_Outer_phi);
   fChain->SetBranchAddress("muon_GLB_pt", &muon_GLB_pt, &b_muon_GLB_pt);
   fChain->SetBranchAddress("muon_GLB_ptError", &muon_GLB_ptError, &b_muon_GLB_ptError);
   fChain->SetBranchAddress("muon_GLB_Px", &muon_GLB_Px, &b_muon_GLB_Px);
   fChain->SetBranchAddress("muon_GLB_Py", &muon_GLB_Py, &b_muon_GLB_Py);
   fChain->SetBranchAddress("muon_GLB_Pz", &muon_GLB_Pz, &b_muon_GLB_Pz);
   fChain->SetBranchAddress("muon_GLB_eta", &muon_GLB_eta, &b_muon_GLB_eta);
   fChain->SetBranchAddress("muon_GLB_phi", &muon_GLB_phi, &b_muon_GLB_phi);
   fChain->SetBranchAddress("muon_TuneP_pt", &muon_TuneP_pt, &b_muon_TuneP_pt);
   fChain->SetBranchAddress("muon_TuneP_ptError", &muon_TuneP_ptError, &b_muon_TuneP_ptError);
   fChain->SetBranchAddress("muon_TuneP_Px", &muon_TuneP_Px, &b_muon_TuneP_Px);
   fChain->SetBranchAddress("muon_TuneP_Py", &muon_TuneP_Py, &b_muon_TuneP_Py);
   fChain->SetBranchAddress("muon_TuneP_Pz", &muon_TuneP_Pz, &b_muon_TuneP_Pz);
   fChain->SetBranchAddress("muon_TuneP_eta", &muon_TuneP_eta, &b_muon_TuneP_eta);
   fChain->SetBranchAddress("muon_TuneP_phi", &muon_TuneP_phi, &b_muon_TuneP_phi);
   fChain->SetBranchAddress("muon_roch_sf", &muon_roch_sf, &b_muon_roch_sf);
   fChain->SetBranchAddress("muon_roch_sf_up", &muon_roch_sf_up, &b_muon_roch_sf_up);
   fChain->SetBranchAddress("muon_PfChargedHadronMiniIso", &muon_PfChargedHadronMiniIso, &b_muon_PfChargedHadronMiniIso);
   fChain->SetBranchAddress("muon_PfNeutralHadronMiniIso", &muon_PfNeutralHadronMiniIso, &b_muon_PfNeutralHadronMiniIso);
   fChain->SetBranchAddress("muon_PfGammaMiniIso", &muon_PfGammaMiniIso, &b_muon_PfGammaMiniIso);
   fChain->SetBranchAddress("muon_PFSumPUMiniIso", &muon_PFSumPUMiniIso, &b_muon_PFSumPUMiniIso);

   if(!IsDATA){
   fChain->SetBranchAddress("PDFWeights_Scale", &PDFWeights_Scale, &b_PDFWeights_Scale);
   fChain->SetBranchAddress("PDFWeights_Error", &PDFWeights_Error, &b_PDFWeights_Error);
   fChain->SetBranchAddress("PDFWeights_AlphaS", &PDFWeights_AlphaS, &b_PDFWeights_AlphaS);
   fChain->SetBranchAddress("gen_phi", &gen_phi, &b_gen_phi);
   fChain->SetBranchAddress("gen_eta", &gen_eta, &b_gen_eta);
   fChain->SetBranchAddress("gen_pt", &gen_pt, &b_gen_pt);
   fChain->SetBranchAddress("gen_Px", &gen_Px, &b_gen_Px);
   fChain->SetBranchAddress("gen_Py", &gen_Py, &b_gen_Py);
   fChain->SetBranchAddress("gen_Pz", &gen_Pz, &b_gen_Pz);
   fChain->SetBranchAddress("gen_E", &gen_E, &b_gen_E);
   fChain->SetBranchAddress("gen_mother_PID", &gen_mother_PID, &b_gen_mother_PID);
   fChain->SetBranchAddress("gen_mother_pt", &gen_mother_pt, &b_gen_mother_pt);
   fChain->SetBranchAddress("gen_mother_index", &gen_mother_index, &b_gen_mother_index);
   fChain->SetBranchAddress("gen_charge", &gen_charge, &b_gen_charge);
   fChain->SetBranchAddress("gen_status", &gen_status, &b_gen_status);
   fChain->SetBranchAddress("gen_PID", &gen_PID, &b_gen_PID);
   fChain->SetBranchAddress("gen_isPrompt", &gen_isPrompt, &b_gen_isPrompt);
   fChain->SetBranchAddress("gen_isPromptFinalState", &gen_isPromptFinalState, &b_gen_isPromptFinalState);
   fChain->SetBranchAddress("gen_isTauDecayProduct", &gen_isTauDecayProduct, &b_gen_isTauDecayProduct);
   fChain->SetBranchAddress("gen_isPromptTauDecayProduct", &gen_isPromptTauDecayProduct, &b_gen_isPromptTauDecayProduct);
   fChain->SetBranchAddress("gen_isDirectPromptTauDecayProductFinalState", &gen_isDirectPromptTauDecayProductFinalState, &b_gen_isDirectPromptTauDecayProductFinalState);
   fChain->SetBranchAddress("gen_isHardProcess", &gen_isHardProcess, &b_gen_isHardProcess);
   fChain->SetBranchAddress("gen_isLastCopy", &gen_isLastCopy, &b_gen_isLastCopy);
   fChain->SetBranchAddress("gen_isLastCopyBeforeFSR", &gen_isLastCopyBeforeFSR, &b_gen_isLastCopyBeforeFSR);
   fChain->SetBranchAddress("gen_isPromptDecayed", &gen_isPromptDecayed, &b_gen_isPromptDecayed);
   fChain->SetBranchAddress("gen_isDecayedLeptonHadron", &gen_isDecayedLeptonHadron, &b_gen_isDecayedLeptonHadron);
   fChain->SetBranchAddress("gen_fromHardProcessBeforeFSR", &gen_fromHardProcessBeforeFSR, &b_gen_fromHardProcessBeforeFSR);
   fChain->SetBranchAddress("gen_fromHardProcessDecayed", &gen_fromHardProcessDecayed, &b_gen_fromHardProcessDecayed);
   fChain->SetBranchAddress("gen_fromHardProcessFinalState", &gen_fromHardProcessFinalState, &b_gen_fromHardProcessFinalState);
   fChain->SetBranchAddress("gen_isMostlyLikePythia6Status3", &gen_isMostlyLikePythia6Status3, &b_gen_isMostlyLikePythia6Status3);
   fChain->SetBranchAddress("gen_weight", &gen_weight, &b_gen_weight);
   fChain->SetBranchAddress("genWeight_Q", &genWeight_Q, &b_genWeight_Q);
   fChain->SetBranchAddress("genWeight_X1", &genWeight_X1, &b_genWeight_X1);
   fChain->SetBranchAddress("genWeight_X2", &genWeight_X2, &b_genWeight_X2);
   fChain->SetBranchAddress("genWeight_id1", &genWeight_id1, &b_genWeight_id1);
   fChain->SetBranchAddress("genWeight_id2", &genWeight_id2, &b_genWeight_id2);
   fChain->SetBranchAddress("genWeight_alphaQCD", &genWeight_alphaQCD, &b_genWeight_alphaQCD);
   fChain->SetBranchAddress("genWeight_alphaQED", &genWeight_alphaQED, &b_genWeight_alphaQED);
   }

   fChain->SetBranchAddress("photon_pt", &photon_pt, &b_photon_pt);
   fChain->SetBranchAddress("photon_eta", &photon_eta, &b_photon_eta);
   fChain->SetBranchAddress("photon_phi", &photon_phi, &b_photon_phi);
   fChain->SetBranchAddress("photon_scEta", &photon_scEta, &b_photon_scEta);
   fChain->SetBranchAddress("photon_scPhi", &photon_scPhi, &b_photon_scPhi);
   fChain->SetBranchAddress("photon_HoverE", &photon_HoverE, &b_photon_HoverE);
   fChain->SetBranchAddress("photon_hasPixelSeed", &photon_hasPixelSeed, &b_photon_hasPixelSeed);
   fChain->SetBranchAddress("photon_Full5x5_SigmaIEtaIEta", &photon_Full5x5_SigmaIEtaIEta, &b_photon_Full5x5_SigmaIEtaIEta);
   fChain->SetBranchAddress("photon_ChIso", &photon_ChIso, &b_photon_ChIso);
   fChain->SetBranchAddress("photon_NhIso", &photon_NhIso, &b_photon_NhIso);
   fChain->SetBranchAddress("photon_PhIso", &photon_PhIso, &b_photon_PhIso);
   fChain->SetBranchAddress("photon_ChIsoWithEA", &photon_ChIsoWithEA, &b_photon_ChIsoWithEA);
   fChain->SetBranchAddress("photon_NhIsoWithEA", &photon_NhIsoWithEA, &b_photon_NhIsoWithEA);
   fChain->SetBranchAddress("photon_PhIsoWithEA", &photon_PhIsoWithEA, &b_photon_PhIsoWithEA);
   fChain->SetBranchAddress("photon_passMVAID_WP80", &photon_passMVAID_WP80, &b_photon_passMVAID_WP80);
   fChain->SetBranchAddress("photon_passMVAID_WP90", &photon_passMVAID_WP90, &b_photon_passMVAID_WP90);
   fChain->SetBranchAddress("photon_passLooseID", &photon_passLooseID, &b_photon_passLooseID);
   fChain->SetBranchAddress("photon_passMediumID", &photon_passMediumID, &b_photon_passMediumID);
   fChain->SetBranchAddress("photon_passTightID", &photon_passTightID, &b_photon_passTightID);
   fChain->SetBranchAddress("photon_ptUnCorr", &photon_ptUnCorr, &b_photon_ptUnCorr);
   fChain->SetBranchAddress("nPileUp", &nPileUp, &b_nPileUp);
   fChain->SetBranchAddress("pileUpReweightIn", &pileUpReweightIn, &b_pileUpReweightIn);
   fChain->SetBranchAddress("pileUpReweight", &pileUpReweight, &b_pileUpReweight);
   fChain->SetBranchAddress("pileUpReweightPlus", &pileUpReweightPlus, &b_pileUpReweightPlus);
   fChain->SetBranchAddress("pileUpReweightMinus", &pileUpReweightMinus, &b_pileUpReweightMinus);
   fChain->SetBranchAddress("pileUpReweightInMuonPhys", &pileUpReweightInMuonPhys, &b_pileUpReweightInMuonPhys);
   fChain->SetBranchAddress("pileUpReweightMuonPhys", &pileUpReweightMuonPhys, &b_pileUpReweightMuonPhys);
   fChain->SetBranchAddress("pileUpReweightPlusMuonPhys", &pileUpReweightPlusMuonPhys, &b_pileUpReweightPlusMuonPhys);
   fChain->SetBranchAddress("pileUpReweightMinusMuonPhys", &pileUpReweightMinusMuonPhys, &b_pileUpReweightMinusMuonPhys);
   fChain->SetBranchAddress("pfMET_pt", &pfMET_pt, &b_pfMET_pt);
   fChain->SetBranchAddress("pfMET_phi", &pfMET_phi, &b_pfMET_phi);
   fChain->SetBranchAddress("pfMET_Px", &pfMET_Px, &b_pfMET_Px);
   fChain->SetBranchAddress("pfMET_Py", &pfMET_Py, &b_pfMET_Py);
   fChain->SetBranchAddress("pfMET_SumEt", &pfMET_SumEt, &b_pfMET_SumEt);
   fChain->SetBranchAddress("pfMET_Type1_pt", &pfMET_Type1_pt, &b_pfMET_Type1_pt);
   fChain->SetBranchAddress("pfMET_Type1_phi", &pfMET_Type1_phi, &b_pfMET_Type1_phi);
   fChain->SetBranchAddress("pfMET_Type1_Px", &pfMET_Type1_Px, &b_pfMET_Type1_Px);
   fChain->SetBranchAddress("pfMET_Type1_Py", &pfMET_Type1_Py, &b_pfMET_Type1_Py);
   fChain->SetBranchAddress("pfMET_Type1_SumEt", &pfMET_Type1_SumEt, &b_pfMET_Type1_SumEt);
   fChain->SetBranchAddress("pfMET_Type1_PhiCor_pt", &pfMET_Type1_PhiCor_pt, &b_pfMET_Type1_PhiCor_pt);
   fChain->SetBranchAddress("pfMET_Type1_PhiCor_phi", &pfMET_Type1_PhiCor_phi, &b_pfMET_Type1_PhiCor_phi);
   fChain->SetBranchAddress("pfMET_Type1_PhiCor_Px", &pfMET_Type1_PhiCor_Px, &b_pfMET_Type1_PhiCor_Px);
   fChain->SetBranchAddress("pfMET_Type1_PhiCor_Py", &pfMET_Type1_PhiCor_Py, &b_pfMET_Type1_PhiCor_Py);
   fChain->SetBranchAddress("pfMET_Type1_PhiCor_SumEt", &pfMET_Type1_PhiCor_SumEt, &b_pfMET_Type1_PhiCor_SumEt);

}












